/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#2fd9f4",
        "outline-variant": "#464554",
        "inverse-primary": "#494bd6",
        "on-tertiary-container": "#272a2c",
        "surface-tint": "#c0c1ff",
        "surface-container-lowest": "#070d1f",
        "on-secondary-container": "#00515d",
        "error-container": "#93000a",
        "secondary-fixed": "#a2eeff",
        "surface-bright": "#33394c",
        "on-primary": "#1000a9",
        "on-secondary-fixed": "#001f25",
        "on-primary-fixed": "#07006c",
        "on-primary-container": "#0d0096",
        "surface-variant": "#2e3447",
        "on-tertiary": "#2d3133",
        "surface-container-highest": "#2e3447",
        "secondary": "#5de6ff",
        "background": "#0c1324",
        "on-secondary": "#00363e",
        "primary": "#c0c1ff",
        "on-secondary-fixed-variant": "#004e5a",
        "tertiary-container": "#8e9193",
        "inverse-surface": "#dce1fb",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "primary-container": "#8083ff",
        "tertiary": "#c4c7c9",
        "error": "#ffb4ab",
        "surface-container-low": "#151b2d",
        "surface": "#0c1324",
        "secondary-container": "#00cbe6",
        "tertiary-fixed": "#e0e3e5",
        "on-surface-variant": "#c7c4d7",
        "surface-container": "#191f31",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-on-surface": "#2a3043",
        "on-background": "#dce1fb",
        "on-tertiary-fixed": "#191c1e",
        "tertiary-fixed-dim": "#c4c7c9",
        "outline": "#908fa0",
        "on-tertiary-fixed-variant": "#444749",
        "surface-container-high": "#23293c",
        "primary-fixed-dim": "#c0c1ff",
        "primary-fixed": "#e1e0ff",
        "surface-dim": "#0c1324",
        "on-surface": "#dce1fb",
        
        // Legacy fallbacks (map old variables to new tokens roughly to avoid completely breaking unmodified components)
        "bg": "#070d1f",
        "surface-legacy": "#0c1324",
        "elevated": "#151b2d",
        "sidebar": "#0c1324",
        "border": "#2e3447",
        "border-strong": "#464554",
        "hover": "rgba(255, 255, 255, 0.05)",
        "hover-strong": "rgba(255, 255, 255, 0.08)",
        "text": "#dce1fb",
        "text-muted": "#c7c4d7",
        "text-subtle": "#908fa0",
        "accent": "#6366f1",
        "danger": "#ffb4ab",
        "success": "#5de6ff",
        "warning": "#00cbe6",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "max-width": "1440px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "unit": "4px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "mono-data": ["Geist", "monospace"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "display-lg-mobile": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "mono-data": ["13px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      },
      animation: {
        'rise': 'rise 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fadeIn 0.2s ease-out forwards',
        'spin': 'spin 1s linear infinite',
      },
      keyframes: {
        rise: {
          '0%': { opacity: '0', transform: 'translateY(10px) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        }
      }
    },
  },
  plugins: [],
}
