/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#2fd9f4",
        "outline-variant": "#2e2e2e",
        "inverse-primary": "#494bd6",
        "on-tertiary-container": "#272a2c",
        "surface-tint": "#fc4c02",
        "surface-container-lowest": "#0a0a0a",
        "on-secondary-container": "#00515d",
        "error-container": "#93000a",
        "secondary-fixed": "#a2eeff",
        "surface-bright": "#242424",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#001f25",
        "on-primary-fixed": "#ffffff",
        "on-primary-container": "#ffffff",
        "surface-variant": "#2e2e2e",
        "on-tertiary": "#2d3133",
        "surface-container-highest": "#2e2e2e",
        "secondary": "#5de6ff",
        "background": "#111111",
        "on-secondary": "#00363e",
        "primary": "#fc4c02",
        "on-secondary-fixed-variant": "#004e5a",
        "tertiary-container": "#8e9193",
        "inverse-surface": "#f3f4f6",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "primary-container": "#ff6b2b",
        "tertiary": "#c4c7c9",
        "error": "#ef4444",
        "surface-container-low": "#111111",
        "surface": "#1a1a1a",
        "secondary-container": "#00cbe6",
        "tertiary-fixed": "#e0e3e5",
        "on-surface-variant": "#9ca3af",
        "surface-container": "#1a1a1a",
        "on-primary-fixed-variant": "#ffffff",
        "inverse-on-surface": "#2a3043",
        "on-background": "#f3f4f6",
        "on-tertiary-fixed": "#191c1e",
        "tertiary-fixed-dim": "#c4c7c9",
        "outline": "#3d3d3d",
        "on-tertiary-fixed-variant": "#444749",
        "surface-container-high": "#242424",
        "primary-fixed-dim": "#fc4c02",
        "primary-fixed": "#ff6b2b",
        "surface-dim": "#111111",
        "on-surface": "#f3f4f6",
        
        // Legacy fallbacks
        "bg": "#111111",
        "surface-legacy": "#1a1a1a",
        "elevated": "#242424",
        "sidebar": "#111111",
        "border": "#2e2e2e",
        "border-strong": "#3d3d3d",
        "hover": "rgba(255, 255, 255, 0.05)",
        "hover-strong": "rgba(255, 255, 255, 0.08)",
        "text": "#f3f4f6",
        "text-muted": "#9ca3af",
        "text-subtle": "#6b7280",
        "accent": "#fc4c02",
        "danger": "#ef4444",
        "success": "#10b981",
        "warning": "#f59e0b",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.375rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "max-width": "1440px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "unit": "4px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "mono-data": ["Inter", "monospace"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "display-lg-mobile": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "mono-data": ["13px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      },
      animation: {
        'rise': 'rise 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fadeIn 0.2s ease-out forwards',
        'spin': 'spin 1s linear infinite',
      },
      keyframes: {
        rise: {
          '0%': { opacity: '0', transform: 'translateY(10px) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        }
      }
    },
  },
  plugins: [],
}
