// AUTO-GENERATED from Jeff Nippard Powerbuilding (Weeks 1-11) + Arm Hypertrophy
// (Block 2 / Week 5, page 12) for the two arm days on Weeks 1-9. 6-day cycle per
// training week: PB / PB / Arm Day / PB / PB / Supplemental A. Week 10 = max test
// (Option A), Week 11 = deload (both PB-only). kg, RPE 1-10. Edit in-app.
import type { WorkoutProgram } from './types';

// Empty default for a brand-new install: the user picks a program from the
// "Your Programs" library (or builds their own). Their data lives in their own
// persisted store + cloud row and is never overwritten by this default.
export const DEFAULT_PROGRAM: WorkoutProgram = {
  name: 'My Program',
  unit: 'kg',
  weeks: [],
  custom: [],
};

// Selectable template in the program library. Arm-day numbers re-verified
// against the Arm Hypertrophy PDF (Block 2 / Week 5, page 12).
export const POWERBUILDING_PROGRAM: WorkoutProgram = {
  name: 'Powerlifting + Arms',
  unit: 'kg',
  weeks: [
  {
    id: "w1",
    name: "Week 1",
    days: [
    {
      id: "w1d1",
      name: "Day 1 — Full Body 1: Squat, Ohp",
      source: "powerbuilding",
      exercises: [
        { id: "w1d1e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 1, reps: "5", percent1RM: "75-80%", rpe: "7.5", rest: "3-4 MIN", notes: "FOCUS ON TECHNIQUE AND EXPLOSIVE POWER!" },
        { id: "w1d1e2", name: "BACK SQUAT", warmupSets: 0, workingSets: 2, reps: "8", percent1RM: "70%", rest: "3-4 MIN", notes: "KEEP BACK ANGLE AND FORM CONSISTENT ACROSS ALL REPS" },
        { id: "w1d1e3", name: "OVERHEAD PRESS", warmupSets: 2, workingSets: 3, reps: "8", percent1RM: "70%", rest: "2-3 MIN", notes: "RESET EACH REP (DON'T TOUCH-AND-PRESS)" },
        { id: "w1d1e4", name: "GLUTE HAM RAISE", warmupSets: 1, workingSets: 3, reps: "8-10", rpe: "7", rest: "1-2 MIN", notes: "KEEP YOUR HIPS STRAIGHT, DO NORDIC HAM CURLS IF NO GHR MACHINE" },
        { id: "w1d1e5", name: "HELMS ROW", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "STRICT FORM. DRIVE ELBOWS OUT AND BACK AT 45 DEGREE ANGLE" },
        { id: "w1d1e6", name: "HAMMER CURL", warmupSets: 0, workingSets: 3, reps: "20-25", rpe: "10", rest: "1-2 MIN", notes: "KEEP ELBOWS LOCKED IN PLACE, SQUEEZE THE DUMBBELL HANDLE HARD!" },
      ],
    },
    {
      id: "w1d2",
      name: "Day 2 — Full Body 2: Deadlift, Bench Press",
      source: "powerbuilding",
      exercises: [
        { id: "w1d2e1", name: "DEADLIFT", warmupSets: 4, workingSets: 3, reps: "4", percent1RM: "80%", rest: "3-5 MIN", notes: "CONVENTIONAL OR SUMO: USE WHATEVER STANCE YOU ARE STRONGER WITH" },
        { id: "w1d2e2", name: "BARBELL BENCH PRESS", warmupSets: 4, workingSets: 1, reps: "3", percent1RM: "82.5-87.5%", rpe: "8.5", rest: "4-5 MIN", notes: "TOP SET. LEAVE 1 (MAYBE 2) REPS IN THE TANK. HARD SET." },
        { id: "w1d2e3", name: "BARBELL BENCH PRESS", warmupSets: 0, workingSets: 2, reps: "10", percent1RM: "67.5%", rest: "2-3 MIN", notes: "QUICK 1 SECOND PAUSE ON THE CHEST ON EACH REP" },
        { id: "w1d2e4", name: "HIP ABDUCTION", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "MACHINE, BAND OR WEIGHTED, 1 SECOND ISOMETRIC HOLD AT THE TOP OF EACH REP" },
        { id: "w1d2e5", name: "WEIGHTED PULL-UP", warmupSets: 1, workingSets: 3, reps: "5-8", rpe: "8", rest: "3-4 MIN", notes: "1.5X SHOULDER WIDTH GRIP, PULL YOUR CHEST TO THE BAR" },
        { id: "w1d2e6", name: "FLOOR SKULL CRUSHER", warmupSets: 1, workingSets: 3, reps: "10-12", rpe: "8", rest: "1-2 MIN", notes: "ARC THE BAR BACK BEHIND YOUR HEAD, SOFT TOUCH ON THE FLOOR BEHIND YOU" },
        { id: "w1d2e7", name: "STANDING CALF RAISE", warmupSets: 1, workingSets: 3, reps: "8-10", rpe: "9", rest: "1-2 MIN", notes: "1-2 SECOND PAUSE AT THE BOTTOM OF EACH REP, FULL ROM" },
      ],
    },
    {
      id: "w1d3",
      name: "Day 3 — Arm Day",
      source: "arms",
      note: "Take the last set of each exercise except close grip bench press to failure.",
      exercises: [
        { id: "w1d3e1", name: "Close Grip Bench Press", workingSets: 4, reps: "4-6", tempo: "2.1.1.1", rpe: "8", rest: "3.0", notes: "Shoulder width grip. Touch bar to chest with a silent pause." },
        { id: "w1d3e2", name: "Bayesian Cable Curl", workingSets: 2, reps: "12-15", tempo: "2.0.2.0", rpe: "7", rest: "1.0", notes: "Pre-activation. Smooth, controlled reps — slight pump with light weight." },
        { id: "w1d3e3", name: "Standing EZ Bar Curl", workingSets: 4, reps: "4-6", tempo: "2.0.1.0", rpe: "9", rest: "3.0", notes: "2 sets wider grip, 2 closer. Last set to failure, 1-2 cheat reps at end." },
        { id: "w1d3e4", name: "Dumbbell Preacher Hammer Curl", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, hammer grip in the middle of the dumbbell." },
        { id: "w1d3e5", name: "Tricep Pressdown", workingSets: 4, reps: "10-12", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Bar attachment. 2 sets wide, 2 narrow. Keep elbows locked." },
        { id: "w1d3e6", name: "Overhead Rope Tricep Extension", workingSets: 2, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, press the rope apart at the top end ROM." },
        { id: "w1d3e7", name: "Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    {
      id: "w1d4",
      name: "Day 4 — Full Body 3: Squat, Dip",
      source: "powerbuilding",
      exercises: [
        { id: "w1d4e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 3, reps: "4", percent1RM: "80%", rest: "3-4 MIN", notes: "MAINTAIN TIGHT PRESSURE IN YOUR UPPER BACK AGAINST THE BAR" },
        { id: "w1d4e2", name: "WEIGHTED DIP", warmupSets: 2, workingSets: 3, reps: "8", rpe: "8", rest: "2-3 MIN", notes: "DO DUMBBELL FLOOR PRESS IF NO ACCESS TO DIP HANDLES" },
        { id: "w1d4e3", name: "HANGING LEG RAISE", warmupSets: 0, workingSets: 3, reps: "10-12", rpe: "9", rest: "1-2 MIN", notes: "KNEES TO CHEST, CONTROLLED REPS, STRAIGHTEN LEGS MORE TO INCREASE DIFFICULTY" },
        { id: "w1d4e4", name: "LAT PULL-OVER", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "8", rest: "1-2 MIN", notes: "CAN USE A DB, CABLE/ROPE OR BAND, STRETCH AND SQUEEZE LATS!" },
        { id: "w1d4e5", name: "INCLINE DUMBBELL CURL", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "DO EACH ARM ONE AT A TIME RATHER THAN ALTERNATING, START WITH YOUR WEAK ARM" },
        { id: "w1d4e6", name: "FACE PULL", warmupSets: 0, workingSets: 4, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "CAN USE CABLE/ROPE OR BAND, RETRACT YOUR SHOULDER BLADES AS YOU PULL" },
      ],
    },
    {
      id: "w1d5",
      name: "Day 5 — Full Body 4: Deadlift, Bench Press",
      source: "powerbuilding",
      exercises: [
        { id: "w1d5e1", name: "PAUSE DEADLIFT", warmupSets: 4, workingSets: 4, reps: "2", percent1RM: "75%", rest: "3-4 MIN", notes: "3 SECOND PAUSE RIGHT AFTER THE PLATES COME OFF THE GROUND" },
        { id: "w1d5e2", name: "PAUSE BARBELL BENCH PRESS", warmupSets: 3, workingSets: 3, reps: "5", percent1RM: "75%", rest: "2-3 MIN", notes: "2-3 SECOND PAUSE ON THE CHEST" },
        { id: "w1d5e3", name: "CHEST-SUPPORTED T-BAR ROW OR PENDLAY ROW", warmupSets: 1, workingSets: 3, reps: "10", rpe: "7", rest: "1-2 MIN", notes: "BE MINDFUL OF LOWER BACK FATIGUE. STAY LIGHT, MINIMIZE CHEATING" },
        { id: "w1d5e4", name: "NORDIC HAM CURL", warmupSets: 0, workingSets: 3, reps: "6-8", rpe: "8", rest: "1-2 MIN", notes: "SEE VIDEO DEMOS PAGE, CAN SUB FOR LYING LEG CURL" },
        { id: "w1d5e5", name: "DUMBBELL SHRUG", warmupSets: 0, workingSets: 3, reps: "20-25", rpe: "9", rest: "1-2 MIN", notes: "FEEL A STRETCH ON THE TRAPS AT THE BOTTOM, SQUEEZE HARD AT THE TOP" },
      ],
    },
    {
      id: "w1d6",
      name: "Day 6 — Supplemental A (Arms)",
      source: "arms",
      note: "Take the last set of each exercise to failure.",
      exercises: [
        { id: "w1d6e1", name: "Dumbbell Concentration Curl", workingSets: 4, reps: "8-10", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Elbow pinned against thigh, rotating grip (supinate through the concentric)." },
        { id: "w1d6e2", name: "Standing EZ Bar Curl (Descending ROM)", workingSets: 2, reps: "10+5+5", rpe: "9", rest: "1.5", notes: "10 reps full ROM, 5 reps top end ROM, 5 reps bottom end ROM." },
        { id: "w1d6e3", name: "Weighted Dip (Close Grip)", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "8", rest: "2.0", notes: "More upright posture, mind-muscle connection with the triceps." },
        { id: "w1d6e4", name: "1-Arm Overhead Cable Extension", workingSets: 2, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Keep your elbow locked into place and tucked in." },
        { id: "w1d6e5", name: "Reverse Grip Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    ],
  },
  {
    id: "w2",
    name: "Week 2",
    days: [
    {
      id: "w2d1",
      name: "Day 1 — Lower #1",
      source: "powerbuilding",
      exercises: [
        { id: "w2d1e1", name: "DEADLIFT", warmupSets: 4, workingSets: 3, reps: "3", percent1RM: "80%", rest: "3-5 MIN", notes: "BRACE YOUR LATS, CHEST TALL, PULL THE SLACK OUT OF THE BAR BEFORE LIFTING" },
        { id: "w2d1e2", name: "SUMO BOX SQUAT OR PAUSE HIGH-BAR SQUAT", warmupSets: 2, workingSets: 2, reps: "8", rpe: "7", rest: "2-3 MIN", notes: "IF YOU SQUAT HIGH-BAR, DO SUMO BOX SQUAT. IF YOU SQUAT LOW-BAR, DO PAUSE HIGH-BAR (2 SEC PAUSE)" },
        { id: "w2d1e3", name: "LEG CURL", warmupSets: 1, workingSets: 3, reps: "6-8", rpe: "8", rest: "1-2 MIN", notes: "DO LYING LEG CURL MACHINE OR NORDIC HAM CURL IF NO MACHINE ACCESS" },
        { id: "w2d1e4", name: "STANDING CALF RAISE", warmupSets: 1, workingSets: 3, reps: "8-10", rpe: "9", rest: "1-2 MIN", notes: "1-2 SECOND PAUSE AT THE BOTTOM OF EACH REP, FULL SQUEEZE AT THE TOP" },
        { id: "w2d1e5", name: "HANGING LEG RAISE", warmupSets: 0, workingSets: 3, reps: "10-12", rpe: "8", rest: "1-2 MIN", notes: "KNEES TO CHEST, CONTROLLED REPS, STRAIGHTEN LEGS MORE TO INCREASE DIFFICULTY" },
      ],
    },
    {
      id: "w2d2",
      name: "Day 2 — Upper #1",
      source: "powerbuilding",
      exercises: [
        { id: "w2d2e1", name: "BARBELL BENCH PRESS", warmupSets: 4, workingSets: 1, reps: "2", percent1RM: "85-90%", rpe: "8", rest: "4-5 MIN", notes: "TOP SET. LEAVE ~2 REPS IN THE TANK. HARD SET." },
        { id: "w2d2e2", name: "BARBELL BENCH PRESS", warmupSets: 0, workingSets: 3, reps: "6", percent1RM: "77.5%", rest: "3-4 MIN", notes: "SET UP A COMFORTABLE ARCH, SLIGHT PAUSE ON THE CHEST, EXPLODE UP" },
        { id: "w2d2e3", name: "CHIN-UP", warmupSets: 1, workingSets: 3, reps: "8-10", rpe: "8", rest: "2-3 MIN", notes: "UNDERHAND GRIP, PULL YOUR CHEST TO THE BAR, ADD WEIGHT IF NEEDED TO HIT RPE" },
        { id: "w2d2e4", name: "OVERHEAD PRESS", warmupSets: 2, workingSets: 3, reps: "4", percent1RM: "80%", rest: "2-3 MIN", notes: "SQUEEZE YOUR GLUTES TO KEEP YOUR TORSO UPRIGHT, PRESS UP AND SLIGHTLY BACK" },
        { id: "w2d2e5", name: "CHEST-SUPPORTED DUMBBELL ROW", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "LIE ON AN INCLINE BENCH AND DO ROWS - PULL WITH LATS!" },
        { id: "w2d2e6", name: "A1: FACE PULL", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "9", rest: "30SEC", notes: "CAN USE CABLE/ROPE OR BAND, RETRACT YOUR SHOULDER BLADES AS YOU PULL" },
        { id: "w2d2e7", name: "A2: DUMBBELL LATERAL RAISE", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "9", rest: "30SEC", notes: "ARC THE DUMBBELL OUT, MIND-MUSCLE CONNECTION WITH MIDDLE FIBERS" },
        { id: "w2d2e8", name: "B1: CONCENTRATION BICEP CURL", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "30SEC", notes: "PIN YOUR ELBOW AGAINST YOUR UPPER LEG OR THE BACK OF A BENCH" },
        { id: "w2d2e9", name: "B2: TRICEPS PRESSDOWN", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "30SEC", notes: "CAN DO WITH CABLES OR BANDS, SQUEEZE TRICEPS TO MOVE THE WEIGHT" },
      ],
    },
    {
      id: "w2d3",
      name: "Day 3 — Arm Day",
      source: "arms",
      note: "Take the last set of each exercise except close grip bench press to failure.",
      exercises: [
        { id: "w2d3e1", name: "Close Grip Bench Press", workingSets: 4, reps: "4-6", tempo: "2.1.1.1", rpe: "8", rest: "3.0", notes: "Shoulder width grip. Touch bar to chest with a silent pause." },
        { id: "w2d3e2", name: "Bayesian Cable Curl", workingSets: 2, reps: "12-15", tempo: "2.0.2.0", rpe: "7", rest: "1.0", notes: "Pre-activation. Smooth, controlled reps — slight pump with light weight." },
        { id: "w2d3e3", name: "Standing EZ Bar Curl", workingSets: 4, reps: "4-6", tempo: "2.0.1.0", rpe: "9", rest: "3.0", notes: "2 sets wider grip, 2 closer. Last set to failure, 1-2 cheat reps at end." },
        { id: "w2d3e4", name: "Dumbbell Preacher Hammer Curl", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, hammer grip in the middle of the dumbbell." },
        { id: "w2d3e5", name: "Tricep Pressdown", workingSets: 4, reps: "10-12", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Bar attachment. 2 sets wide, 2 narrow. Keep elbows locked." },
        { id: "w2d3e6", name: "Overhead Rope Tricep Extension", workingSets: 2, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, press the rope apart at the top end ROM." },
        { id: "w2d3e7", name: "Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    {
      id: "w2d4",
      name: "Day 4 — Lower # 2",
      source: "powerbuilding",
      exercises: [
        { id: "w2d4e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 3, reps: "6", percent1RM: "75%", rest: "3-4 MIN", notes: "SIT BACK AND DOWN, KEEP YOUR UPPER BACK TIGHT TO THE BAR" },
        { id: "w2d4e2", name: "SNATCH-GRIP ROMANIAN DEADLIFT", warmupSets: 2, workingSets: 3, reps: "10", rpe: "7", rest: "2-3 MIN", notes: "WIDE GRIP, MIND-MUSCLE CONNECTION WITH HAMSTRINGS" },
        { id: "w2d4e3", name: "LEG EXTENSION", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "USE BANDS IF NO MACHINE ACCESS, MIND-MUSCLE CONNECTION WITH QUADS" },
        { id: "w2d4e4", name: "STANDING CALF RAISE", warmupSets: 0, workingSets: 4, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "EMPHASIZE THE MIND-MUSCLE CONNECTION" },
        { id: "w2d4e5", name: "BANDED LATERAL WALK OR HIP ABDUCTION", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "POINT TOES SLIGHTLY OUTWARD, MIND-MUSCLE CONNECTION WITH GLUTES" },
        { id: "w2d4e6", name: "V SIT-UP", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "THINK ABOUT SQUEEZING YOUR UPPER AND LOWER ABS TOGETHER" },
        { id: "w2d4e7", name: "NECK FLEXION/EXTENSION (OPTIONAL)", warmupSets: 1, workingSets: 3, reps: "12/12", rpe: "8", rest: "1-2 MIN", notes: "12 REPS FLEXION (FRONT OF NECK), 12 REPS EXTENSION (BACK OF NECK)" },
      ],
    },
    {
      id: "w2d5",
      name: "Day 5 — Upper #2",
      source: "powerbuilding",
      exercises: [
        { id: "w2d5e1", name: "CLOSE-GRIP BENCH PRESS", warmupSets: 3, workingSets: 3, reps: "12", rpe: "7", rest: "2-3 MIN", notes: "SHOULDER WIDTH GRIP, TUCK YOUR ELBOWS IN CLOSER TO YOUR TORSO" },
        { id: "w2d5e2", name: "PENDLAY ROW", warmupSets: 1, workingSets: 3, reps: "10", rpe: "7", rest: "2-3 MIN", notes: "BE MINDFUL OF LOWER BACK FATIGUE. STAY LIGHT, MINIMIZE CHEATING" },
        { id: "w2d5e3", name: "WEIGHTED DIP", warmupSets: 2, workingSets: 3, reps: "6", rpe: "7", rest: "2-3 MIN", notes: "DO DUMBBELL FLOOR PRESS IF NO ACCESS TO DIP HANDLES" },
        { id: "w2d5e4", name: "ECCENTRIC-ACCENTUATED PULL-UP", warmupSets: 1, workingSets: 2, reps: "AMRAP", rpe: "10", rest: "2-3 MIN", notes: "3 SECOND NEGATIVE ON EVERY REP, MAINTAIN CONTROLLED FORM FOR ALL REPS" },
        { id: "w2d5e5", name: "A1. INCLINE SHRUG", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "9", rest: "30SEC", notes: "LIE FACE DOWN AGAINST AN INCLINE BENCH AND DO SHRUGS - FULL ROM AND SQUEEZE!" },
        { id: "w2d5e6", name: "A2. UPRIGHT ROW", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "9", rest: "30SEC", notes: "CAN USE CABLES/ROPE, BANDS OR DUMBBELLS. STOP ROM ONCE ELBOWS REACH SHOULDER HEIGHT." },
        { id: "w2d5e7", name: "B1: BARBELL OR EZ BAR CURL", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "30SEC", notes: "FOCUS ON THE MIND-MUSCLE CONNECTION" },
        { id: "w2d5e8", name: "B2. SKULL CRUSHER", warmupSets: 0, workingSets: 3, reps: "8-10", rpe: "8", rest: "30SEC", notes: "BARBELL OR EZ BAR, DO THESE ON A BENCH, CONSTANT TENSION ON TRICEPS" },
      ],
    },
    {
      id: "w2d6",
      name: "Day 6 — Supplemental A (Arms)",
      source: "arms",
      note: "Take the last set of each exercise to failure.",
      exercises: [
        { id: "w2d6e1", name: "Dumbbell Concentration Curl", workingSets: 4, reps: "8-10", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Elbow pinned against thigh, rotating grip (supinate through the concentric)." },
        { id: "w2d6e2", name: "Standing EZ Bar Curl (Descending ROM)", workingSets: 2, reps: "10+5+5", rpe: "9", rest: "1.5", notes: "10 reps full ROM, 5 reps top end ROM, 5 reps bottom end ROM." },
        { id: "w2d6e3", name: "Weighted Dip (Close Grip)", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "8", rest: "2.0", notes: "More upright posture, mind-muscle connection with the triceps." },
        { id: "w2d6e4", name: "1-Arm Overhead Cable Extension", workingSets: 2, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Keep your elbow locked into place and tucked in." },
        { id: "w2d6e5", name: "Reverse Grip Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    ],
  },
  {
    id: "w3",
    name: "Week 3",
    days: [
    {
      id: "w3d1",
      name: "Day 1 — Full Body 1: Squat, Ohp",
      source: "powerbuilding",
      exercises: [
        { id: "w3d1e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 1, reps: "8", percent1RM: "72.5-77.5%", rpe: "8.5", rest: "3-4 MIN", notes: "TOP SET. LEAVE 1 (MAYBE 2) REPS IN THE TANK. PUSH IT!" },
        { id: "w3d1e2", name: "BACK SQUAT", warmupSets: 0, workingSets: 2, reps: "6", percent1RM: "75%", rest: "3-4 MIN", notes: "KEEP BACK ANGLE AND FORM CONSISTENT ACROSS ALL REPS" },
        { id: "w3d1e3", name: "OVERHEAD PRESS", warmupSets: 2, workingSets: 3, reps: "8", percent1RM: "72.5%", rest: "2-3 MIN", notes: "RESET EACH REP (DON'T TOUCH-AND-PRESS)" },
        { id: "w3d1e4", name: "GLUTE HAM RAISE", warmupSets: 1, workingSets: 2, reps: "8-10", rpe: "7", rest: "1-2 MIN", notes: "KEEP YOUR HIPS STRAIGHT, DO NORDIC HAM CURLS IF NO GHR MACHINE" },
        { id: "w3d1e5", name: "HELMS ROW", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "STRICT FORM. DRIVE ELBOWS OUT AND BACK AT 45 DEGREE ANGLE" },
        { id: "w3d1e6", name: "HAMMER CURL", warmupSets: 0, workingSets: 2, reps: "20-25", rpe: "10", rest: "1-2 MIN", notes: "KEEP ELBOWS LOCKED IN PLACE, SQUEEZE THE DUMBBELL HANDLE HARD!" },
      ],
    },
    {
      id: "w3d2",
      name: "Day 2 — Full Body 2: Deadlift, Bench Press",
      source: "powerbuilding",
      exercises: [
        { id: "w3d2e1", name: "DEADLIFT", warmupSets: 4, workingSets: 4, reps: "2", percent1RM: "85%", rest: "3-5 MIN", notes: "CONVENTIONAL OR SUMO: USE WHATEVER STANCE YOU ARE STRONGER WITH" },
        { id: "w3d2e2", name: "BARBELL BENCH PRESS", warmupSets: 3, workingSets: 1, reps: "6", percent1RM: "75-80%", rpe: "8.5", rest: "4-5 MIN", notes: "TOP SET. LEAVE 1 (MAYBE 2) REPS IN THE TANK. PUSH IT!" },
        { id: "w3d2e3", name: "BARBELL BENCH PRESS", warmupSets: 0, workingSets: 2, reps: "8", percent1RM: "72.5%", rest: "2-3 MIN", notes: "QUICK 1 SECOND PAUSE ON THE CHEST ON EACH REP" },
        { id: "w3d2e4", name: "HIP ABDUCTION", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "MACHINE, BAND OR WEIGHTED, 1 SECOND ISOMETRIC HOLD AT THE TOP OF EACH REP" },
        { id: "w3d2e5", name: "WEIGHTED PULL-UP", warmupSets: 1, workingSets: 3, reps: "5-8", rpe: "8", rest: "3-4 MIN", notes: "1.5X SHOULDER WIDTH GRIP, PULL YOUR CHEST TO THE BAR" },
        { id: "w3d2e6", name: "FLOOR SKULL CRUSHER", warmupSets: 1, workingSets: 3, reps: "10-12", rpe: "8", rest: "1-2 MIN", notes: "ARC THE BAR BACK BEHIND YOUR HEAD, SOFT TOUCH ON THE FLOOR BEHIND YOU" },
        { id: "w3d2e7", name: "STANDING CALF RAISE", warmupSets: 1, workingSets: 3, reps: "8", rpe: "9", rest: "1-2 MIN", notes: "1-2 SECOND PAUSE AT THE BOTTOM OF EACH REP, FULL ROM" },
      ],
    },
    {
      id: "w3d3",
      name: "Day 3 — Arm Day",
      source: "arms",
      note: "Take the last set of each exercise except close grip bench press to failure.",
      exercises: [
        { id: "w3d3e1", name: "Close Grip Bench Press", workingSets: 4, reps: "4-6", tempo: "2.1.1.1", rpe: "8", rest: "3.0", notes: "Shoulder width grip. Touch bar to chest with a silent pause." },
        { id: "w3d3e2", name: "Bayesian Cable Curl", workingSets: 2, reps: "12-15", tempo: "2.0.2.0", rpe: "7", rest: "1.0", notes: "Pre-activation. Smooth, controlled reps — slight pump with light weight." },
        { id: "w3d3e3", name: "Standing EZ Bar Curl", workingSets: 4, reps: "4-6", tempo: "2.0.1.0", rpe: "9", rest: "3.0", notes: "2 sets wider grip, 2 closer. Last set to failure, 1-2 cheat reps at end." },
        { id: "w3d3e4", name: "Dumbbell Preacher Hammer Curl", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, hammer grip in the middle of the dumbbell." },
        { id: "w3d3e5", name: "Tricep Pressdown", workingSets: 4, reps: "10-12", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Bar attachment. 2 sets wide, 2 narrow. Keep elbows locked." },
        { id: "w3d3e6", name: "Overhead Rope Tricep Extension", workingSets: 2, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, press the rope apart at the top end ROM." },
        { id: "w3d3e7", name: "Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    {
      id: "w3d4",
      name: "Day 4 — Full Body 3: Squat, Dip",
      source: "powerbuilding",
      exercises: [
        { id: "w3d4e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 4, reps: "4", percent1RM: "80%", rest: "3-4 MIN", notes: "MAINTAIN TIGHT PRESSURE IN YOUR UPPER BACK AGAINST THE BAR" },
        { id: "w3d4e2", name: "WEIGHTED DIP", warmupSets: 2, workingSets: 3, reps: "8", rpe: "8", rest: "2-3 MIN", notes: "DO DUMBBELL FLOOR PRESS IF NO ACCESS TO DIP HANDLES" },
        { id: "w3d4e3", name: "HANGING LEG RAISE", warmupSets: 0, workingSets: 3, reps: "10-12", rpe: "9", rest: "1-2 MIN", notes: "KNEES TO CHEST, CONTROLLED REPS, STRAIGHTEN LEGS MORE TO INCREASE DIFFICULTY" },
        { id: "w3d4e4", name: "LAT PULL-OVER", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "8", rest: "1-2 MIN", notes: "CAN USE A DB, CABLE/ROPE OR BAND, STRETCH AND SQUEEZE LATS!" },
        { id: "w3d4e5", name: "INCLINE DUMBBELL CURL", warmupSets: 1, workingSets: 2, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "DO EACH ARM ONE AT A TIME RATHER THAN ALTERNATING, START WITH YOUR WEAK ARM" },
        { id: "w3d4e6", name: "FACE PULL", warmupSets: 0, workingSets: 4, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "CAN USE CABLE/ROPE OR BAND, RETRACT YOUR SHOULDER BLADES AS YOU PULL" },
      ],
    },
    {
      id: "w3d5",
      name: "Day 5 — Full Body 4: Deadlift, Bench Press",
      source: "powerbuilding",
      exercises: [
        { id: "w3d5e1", name: "PAUSE DEADLIFT", warmupSets: 4, workingSets: 4, reps: "2", percent1RM: "77.5%", rest: "3-4 MIN", notes: "3 SECOND PAUSE RIGHT AFTER THE PLATES COME OFF THE GROUND" },
        { id: "w3d5e2", name: "PAUSE BARBELL BENCH PRESS", warmupSets: 3, workingSets: 4, reps: "5", percent1RM: "75%", rest: "2-3 MIN", notes: "2-3 SECOND PAUSE ON THE CHEST" },
        { id: "w3d5e3", name: "CHEST-SUPPORTED T-BAR ROW OR PENDLAY ROW", warmupSets: 1, workingSets: 3, reps: "10", rpe: "7", rest: "1-2 MIN", notes: "BE MINDFUL OF LOWER BACK FATIGUE. STAY LIGHT, MINIMIZE CHEATING" },
        { id: "w3d5e4", name: "NORDIC HAM CURL", warmupSets: 0, workingSets: 3, reps: "6-8", rpe: "8", rest: "1-2 MIN", notes: "BEND FORWARD AT HIPS DURING THE CONCENTRIC AND MINIMIZE CONTRIBUTION FROM HANDS" },
        { id: "w3d5e5", name: "DUMBBELL SHRUG", warmupSets: 0, workingSets: 3, reps: "20-25", rpe: "9", rest: "1-2 MIN", notes: "FEEL A STRETCH ON THE TRAPS AT THE BOTTOM, SQUEEZE HARD AT THE TOP" },
      ],
    },
    {
      id: "w3d6",
      name: "Day 6 — Supplemental A (Arms)",
      source: "arms",
      note: "Take the last set of each exercise to failure.",
      exercises: [
        { id: "w3d6e1", name: "Dumbbell Concentration Curl", workingSets: 4, reps: "8-10", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Elbow pinned against thigh, rotating grip (supinate through the concentric)." },
        { id: "w3d6e2", name: "Standing EZ Bar Curl (Descending ROM)", workingSets: 2, reps: "10+5+5", rpe: "9", rest: "1.5", notes: "10 reps full ROM, 5 reps top end ROM, 5 reps bottom end ROM." },
        { id: "w3d6e3", name: "Weighted Dip (Close Grip)", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "8", rest: "2.0", notes: "More upright posture, mind-muscle connection with the triceps." },
        { id: "w3d6e4", name: "1-Arm Overhead Cable Extension", workingSets: 2, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Keep your elbow locked into place and tucked in." },
        { id: "w3d6e5", name: "Reverse Grip Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    ],
  },
  {
    id: "w4",
    name: "Week 4",
    days: [
    {
      id: "w4d1",
      name: "Day 1 — Lower #1",
      source: "powerbuilding",
      exercises: [
        { id: "w4d1e1", name: "DEADLIFT", warmupSets: 4, workingSets: 1, reps: "2", percent1RM: "87.5-92.5%", rpe: "9", rest: "4-5 MIN", notes: "TOP SET! AIM FOR NEAR PR. KEEP FORM TIGHT." },
        { id: "w4d1e2", name: "DEADLIFT", warmupSets: 0, workingSets: 3, reps: "3", percent1RM: "80%", rest: "3-5 MIN", notes: "BRACE YOUR LATS, CHEST TALL, PULL THE SLACK OUT OF THE BAR BEFORE LIFTING" },
        { id: "w4d1e3", name: "SUMO BOX SQUAT OR PAUSE HIGH-BAR SQUAT", warmupSets: 2, workingSets: 2, reps: "8", rpe: "7", rest: "2-3 MIN", notes: "IF YOU SQUAT HIGH-BAR, DO SUMO BOX SQUAT. IF YOU SQUAT LOW-BAR, DO PAUSE HIGH-BAR (2 SEC PAUSE)" },
        { id: "w4d1e4", name: "LEG CURL", warmupSets: 1, workingSets: 3, reps: "6-8", rpe: "8", rest: "1-2 MIN", notes: "DO LYING LEG CURL MACHINE OR NORDIC HAM CURL IF NO MACHINE ACCESS" },
        { id: "w4d1e5", name: "STANDING CALF RAISE", warmupSets: 1, workingSets: 3, reps: "8-10", rpe: "9", rest: "1-2 MIN", notes: "1-2 SECOND PAUSE AT THE BOTTOM OF EACH REP, FULL SQUEEZE AT THE TOP" },
        { id: "w4d1e6", name: "HANGING LEG RAISE", warmupSets: 0, workingSets: 3, reps: "10-12", rpe: "8", rest: "1-2 MIN", notes: "KNEES TO CHEST, CONTROLLED REPS, STRAIGHTEN LEGS MORE TO INCREASE DIFFICULTY" },
      ],
    },
    {
      id: "w4d2",
      name: "Day 2 — Upper #1",
      source: "powerbuilding",
      exercises: [
        { id: "w4d2e1", name: "FLAT-BACK BENCH PRESS", warmupSets: 3, workingSets: 3, reps: "10", rpe: "7", rest: "3-4 MIN", notes: "SHOULDER BLADES STILL RETRACTED AND DEPRESSED. SLIGHT ARCH IN UPPER BACK. MINIMIZE LEG DRIVE." },
        { id: "w4d2e2", name: "CHIN-UP", warmupSets: 1, workingSets: 3, reps: "8-10", rpe: "8", rest: "2-3 MIN", notes: "UNDERHAND GRIP, PULL YOUR CHEST TO THE BAR, ADD WEIGHT IF NEEDED TO HIT RPE" },
        { id: "w4d2e3", name: "OVERHEAD PRESS / PUSH PRESS", warmupSets: 2, workingSets: 3, reps: "3/3", percent1RM: "80%", rest: "2-3 MIN", notes: "FIRST 3 REPS STRICT MILITARY PRESS (NO LEG DRIVE), LAST 3 REPS PUSH PRESS (USE LEG DRIVE)" },
        { id: "w4d2e4", name: "CHEST-SUPPORTED DUMBBELL ROW", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "LIE ON AN INCLINE BENCH AND DO ROWS - PULL WITH LATS!" },
        { id: "w4d2e5", name: "A1: FACE PULL", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "30SEC", notes: "CAN USE CABLE/ROPE OR BAND, RETRACT YOUR SHOULDER BLADES AS YOU PULL" },
        { id: "w4d2e6", name: "A2: DUMBBELL LATERAL RAISE", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "30SEC", notes: "ARC THE DUMBBELL OUT, MIND-MUSCLE CONNECTION WITH MIDDLE FIBERS" },
        { id: "w4d2e7", name: "B1: CONCENTRATION BICEP CURL", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "30SEC", notes: "PIN YOUR ELBOW AGAINST YOUR UPPER LEG OR THE BACK OF A BENCH" },
        { id: "w4d2e8", name: "B2: TRICEPS PRESSDOWN", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "30SEC", notes: "CAN DO WITH CABLES OR BANDS, SQUEEZE TRICEPS TO MOVE THE WEIGHT" },
      ],
    },
    {
      id: "w4d3",
      name: "Day 3 — Arm Day",
      source: "arms",
      note: "Take the last set of each exercise except close grip bench press to failure.",
      exercises: [
        { id: "w4d3e1", name: "Close Grip Bench Press", workingSets: 4, reps: "4-6", tempo: "2.1.1.1", rpe: "8", rest: "3.0", notes: "Shoulder width grip. Touch bar to chest with a silent pause." },
        { id: "w4d3e2", name: "Bayesian Cable Curl", workingSets: 2, reps: "12-15", tempo: "2.0.2.0", rpe: "7", rest: "1.0", notes: "Pre-activation. Smooth, controlled reps — slight pump with light weight." },
        { id: "w4d3e3", name: "Standing EZ Bar Curl", workingSets: 4, reps: "4-6", tempo: "2.0.1.0", rpe: "9", rest: "3.0", notes: "2 sets wider grip, 2 closer. Last set to failure, 1-2 cheat reps at end." },
        { id: "w4d3e4", name: "Dumbbell Preacher Hammer Curl", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, hammer grip in the middle of the dumbbell." },
        { id: "w4d3e5", name: "Tricep Pressdown", workingSets: 4, reps: "10-12", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Bar attachment. 2 sets wide, 2 narrow. Keep elbows locked." },
        { id: "w4d3e6", name: "Overhead Rope Tricep Extension", workingSets: 2, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, press the rope apart at the top end ROM." },
        { id: "w4d3e7", name: "Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    {
      id: "w4d4",
      name: "Day 4 — Lower # 2",
      source: "powerbuilding",
      exercises: [
        { id: "w4d4e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 3, reps: "6", percent1RM: "75%", rest: "3-4 MIN", notes: "SIT BACK AND DOWN, KEEP YOUR UPPER BACK TIGHT TO THE BAR" },
        { id: "w4d4e2", name: "5\" BLOCK PULL", warmupSets: 3, workingSets: 2, reps: "4", rpe: "8", rest: "2-3 MIN", notes: "DO BLOCK PULLS FROM A 5\" BLOCK (CAN STACK 45LB + 10LB BUMPER PLATES AS BLOCKS)" },
        { id: "w4d4e3", name: "LEG EXTENSION", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "USE BANDS IF NO MACHINE ACCESS, MIND-MUSCLE CONNECTION WITH QUADS" },
        { id: "w4d4e4", name: "STANDING CALF RAISE", warmupSets: 0, workingSets: 4, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "EMPHASIZE THE MIND-MUSCLE CONNECTION" },
        { id: "w4d4e5", name: "BANDED LATERAL WALK OR HIP ABDUCTION", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "POINT TOES SLIGHTLY OUTWARD, MIND-MUSCLE CONNECTION WITH GLUTES" },
        { id: "w4d4e6", name: "V SIT-UP", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "THINK ABOUT SQUEEZING YOUR UPPER AND LOWER ABS TOGETHER" },
        { id: "w4d4e7", name: "NECK FLEXION/EXTENSION (OPTIONAL)", warmupSets: 1, workingSets: 3, reps: "12/12", rpe: "8", rest: "1-2 MIN", notes: "12 REPS FLEXION (FRONT OF NECK), 12 REPS EXTENSION (BACK OF NECK)" },
      ],
    },
    {
      id: "w4d5",
      name: "Day 5 — Upper #2",
      source: "powerbuilding",
      exercises: [
        { id: "w4d5e1", name: "WEIGHTED DIP", warmupSets: 2, workingSets: 3, reps: "6", rpe: "7", rest: "2-3 MIN", notes: "DO INCLINE DUMBBELL PRESS IF NO ACCESS TO DIP HANDLES" },
        { id: "w4d5e2", name: "PENDLAY ROW", warmupSets: 1, workingSets: 3, reps: "10", rpe: "7", rest: "2-3 MIN", notes: "BE MINDFUL OF LOWER BACK FATIGUE. STAY LIGHT, MINIMIZE CHEATING" },
        { id: "w4d5e3", name: "DEFICIT PUSH-UP", warmupSets: 2, workingSets: 2, reps: "AMRAP", rpe: "7", rest: "2-3 MIN", notes: "AS MANY REPS AS POSSIBLE. USE PERFECT PUSH-UP HANDLES OR DUMBBELLS TO CREATE A DEFICIT" },
        { id: "w4d5e4", name: "ECCENTRIC-ACCENTUATED PULL-UP", warmupSets: 1, workingSets: 2, reps: "AMRAP", rpe: "10", rest: "2-3 MIN", notes: "3 SECOND NEGATIVE ON EVERY REP, MAINTAIN CONTROLLED FORM FOR ALL REPS" },
        { id: "w4d5e5", name: "A1. INCLINE SHRUG", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "9", rest: "30SEC", notes: "LIE FACE DOWN AGAINST AN INCLINE BENCH AND DO SHRUGS - FULL ROM AND SQUEEZE!" },
        { id: "w4d5e6", name: "A2. BENT OVER REVERSE DUMBBELL FLYE", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "9", rest: "30SEC", notes: "MIND-MUSCLE CONNECTION WITH REAR DELTS, SWEEP THE WEIGHT OUT" },
        { id: "w4d5e7", name: "B1: BARBELL OR EZ BAR CURL", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "30SEC", notes: "FOCUS ON THE MIND-MUSCLE CONNECTION" },
        { id: "w4d5e8", name: "B2. SKULL CRUSHER", warmupSets: 0, workingSets: 3, reps: "8-10", rpe: "9", rest: "30SEC", notes: "BARBELL OR EZ BAR, DO THESE ON A BENCH, CONSTANT TENSION ON TRICEPS" },
      ],
    },
    {
      id: "w4d6",
      name: "Day 6 — Supplemental A (Arms)",
      source: "arms",
      note: "Take the last set of each exercise to failure.",
      exercises: [
        { id: "w4d6e1", name: "Dumbbell Concentration Curl", workingSets: 4, reps: "8-10", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Elbow pinned against thigh, rotating grip (supinate through the concentric)." },
        { id: "w4d6e2", name: "Standing EZ Bar Curl (Descending ROM)", workingSets: 2, reps: "10+5+5", rpe: "9", rest: "1.5", notes: "10 reps full ROM, 5 reps top end ROM, 5 reps bottom end ROM." },
        { id: "w4d6e3", name: "Weighted Dip (Close Grip)", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "8", rest: "2.0", notes: "More upright posture, mind-muscle connection with the triceps." },
        { id: "w4d6e4", name: "1-Arm Overhead Cable Extension", workingSets: 2, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Keep your elbow locked into place and tucked in." },
        { id: "w4d6e5", name: "Reverse Grip Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    ],
  },
  {
    id: "w5",
    name: "Week 5",
    days: [
    {
      id: "w5d1",
      name: "Day 1 — Full Body 1: Squat, Ohp",
      source: "powerbuilding",
      exercises: [
        { id: "w5d1e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 1, reps: "3", percent1RM: "82.5-87.5%", rpe: "8.5", rest: "3-4 MIN", notes: "TOP SET. LEAVE 1 (MAYBE 2) REPS IN THE TANK. AIM FOR NEAR 3 REP PR." },
        { id: "w5d1e2", name: "BACK SQUAT", warmupSets: 0, workingSets: 2, reps: "4", percent1RM: "80%", rest: "3-4 MIN", notes: "KEEP BACK ANGLE AND FORM CONSISTENT ACROSS ALL REPS" },
        { id: "w5d1e3", name: "OVERHEAD PRESS", warmupSets: 2, workingSets: 3, reps: "8", percent1RM: "75%", rest: "2-3 MIN", notes: "RESET EACH REP (DON'T TOUCH-AND-PRESS)" },
        { id: "w5d1e4", name: "GLUTE HAM RAISE", warmupSets: 1, workingSets: 2, reps: "8-10", rpe: "8", rest: "1-2 MIN", notes: "KEEP YOUR HIPS STRAIGHT, DO NORDIC HAM CURLS IF NO GHR MACHINE" },
        { id: "w5d1e5", name: "HELMS ROW", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "STRICT FORM. DRIVE ELBOWS OUT AND BACK AT 45 DEGREE ANGLE" },
        { id: "w5d1e6", name: "HAMMER CURL", warmupSets: 0, workingSets: 2, reps: "20-25", rpe: "10", rest: "1-2 MIN", notes: "KEEP ELBOWS LOCKED IN PLACE, SQUEEZE THE DUMBBELL HANDLE HARD!" },
      ],
    },
    {
      id: "w5d2",
      name: "Day 2 — Full Body 2: Deadlift, Bench Press",
      source: "powerbuilding",
      exercises: [
        { id: "w5d2e1", name: "DEADLIFT", warmupSets: 4, workingSets: 3, reps: "3", percent1RM: "85%", rest: "3-5 MIN", notes: "BRACE YOUR LATS, CHEST TALL, PULL THE SLACK OUT OF THE BAR BEFORE LIFTING" },
        { id: "w5d2e2", name: "BARBELL BENCH PRESS", warmupSets: 3, workingSets: 1, reps: "4", percent1RM: "82.5-87.5%", rpe: "9", rest: "4-5 MIN", notes: "TOP SET. LEAVE 1 REP IN THE TANK. AIM FOR NEAR 4 REP PR." },
        { id: "w5d2e3", name: "BARBELL BENCH PRESS", warmupSets: 0, workingSets: 2, reps: "6", percent1RM: "80%", rest: "2-3 MIN", notes: "QUICK 1 SECOND PAUSE ON THE CHEST ON EACH REP" },
        { id: "w5d2e4", name: "HIP ABDUCTION", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "MACHINE, BAND OR WEIGHTED, 1 SECOND ISOMETRIC HOLD AT THE TOP OF EACH REP" },
        { id: "w5d2e5", name: "WEIGHTED PULL-UP", warmupSets: 1, workingSets: 3, reps: "5-8", rpe: "8", rest: "3-4 MIN", notes: "1.5X SHOULDER WIDTH GRIP, PULL YOUR CHEST TO THE BAR" },
        { id: "w5d2e6", name: "FLOOR SKULL CRUSHER", warmupSets: 1, workingSets: 3, reps: "10-12", rpe: "8", rest: "1-2 MIN", notes: "ARC THE BAR BACK BEHIND YOUR HEAD, SOFT TOUCH ON THE FLOOR BEHIND YOU" },
        { id: "w5d2e7", name: "STANDING CALF RAISE", warmupSets: 1, workingSets: 3, reps: "8", rpe: "9", rest: "1-2 MIN", notes: "1-2 SECOND PAUSE AT THE BOTTOM OF EACH REP, FULL ROM" },
      ],
    },
    {
      id: "w5d3",
      name: "Day 3 — Arm Day",
      source: "arms",
      note: "Take the last set of each exercise except close grip bench press to failure.",
      exercises: [
        { id: "w5d3e1", name: "Close Grip Bench Press", workingSets: 4, reps: "4-6", tempo: "2.1.1.1", rpe: "8", rest: "3.0", notes: "Shoulder width grip. Touch bar to chest with a silent pause." },
        { id: "w5d3e2", name: "Bayesian Cable Curl", workingSets: 2, reps: "12-15", tempo: "2.0.2.0", rpe: "7", rest: "1.0", notes: "Pre-activation. Smooth, controlled reps — slight pump with light weight." },
        { id: "w5d3e3", name: "Standing EZ Bar Curl", workingSets: 4, reps: "4-6", tempo: "2.0.1.0", rpe: "9", rest: "3.0", notes: "2 sets wider grip, 2 closer. Last set to failure, 1-2 cheat reps at end." },
        { id: "w5d3e4", name: "Dumbbell Preacher Hammer Curl", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, hammer grip in the middle of the dumbbell." },
        { id: "w5d3e5", name: "Tricep Pressdown", workingSets: 4, reps: "10-12", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Bar attachment. 2 sets wide, 2 narrow. Keep elbows locked." },
        { id: "w5d3e6", name: "Overhead Rope Tricep Extension", workingSets: 2, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, press the rope apart at the top end ROM." },
        { id: "w5d3e7", name: "Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    {
      id: "w5d4",
      name: "Day 4 — Full Body 3: Squat, Dip",
      source: "powerbuilding",
      exercises: [
        { id: "w5d4e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 3, reps: "6", percent1RM: "77.5%", rest: "3-4 MIN", notes: "MAINTAIN TIGHT PRESSURE IN YOUR UPPER BACK AGAINST THE BAR" },
        { id: "w5d4e2", name: "WEIGHTED DIP", warmupSets: 2, workingSets: 3, reps: "8", rpe: "8", rest: "2-3 MIN", notes: "DO DUMBBELL FLOOR PRESS IF NO ACCESS TO DIP HANDLES" },
        { id: "w5d4e3", name: "HANGING LEG RAISE", warmupSets: 0, workingSets: 3, reps: "10-12", rpe: "9", rest: "1-2 MIN", notes: "KNEES TO CHEST, CONTROLLED REPS, STRAIGHTEN LEGS MORE TO INCREASE DIFFICULTY" },
        { id: "w5d4e4", name: "LAT PULL-OVER", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "CAN USE A DB, CABLE/ROPE OR BAND, STRETCH AND SQUEEZE LATS!" },
        { id: "w5d4e5", name: "INCLINE DUMBBELL CURL", warmupSets: 1, workingSets: 2, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "DO EACH ARM ONE AT A TIME RATHER THAN ALTERNATING, START WITH YOUR WEAK ARM" },
        { id: "w5d4e6", name: "FACE PULL", warmupSets: 0, workingSets: 4, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "CAN USE CABLE/ROPE OR BAND, RETRACT YOUR SHOULDER BLADES AS YOU PULL" },
      ],
    },
    {
      id: "w5d5",
      name: "Day 5 — Full Body 4: Deadlift, Bench Press",
      source: "powerbuilding",
      exercises: [
        { id: "w5d5e1", name: "PAUSE DEADLIFT", warmupSets: 4, workingSets: 4, reps: "2", percent1RM: "82.5%", rest: "3-4 MIN", notes: "3 SECOND PAUSE RIGHT AFTER THE PLATES COME OFF THE GROUND" },
        { id: "w5d5e2", name: "PAUSE BARBELL BENCH PRESS", warmupSets: 3, workingSets: 3, reps: "6", percent1RM: "75%", rest: "2-3 MIN", notes: "2-3 SECOND PAUSE ON THE CHEST" },
        { id: "w5d5e3", name: "CHEST-SUPPORTED T-BAR ROW OR PENDLAY ROW", warmupSets: 1, workingSets: 3, reps: "10", rpe: "7", rest: "1-2 MIN", notes: "BE MINDFUL OF LOWER BACK FATIGUE. STAY LIGHT, MINIMIZE CHEATING" },
        { id: "w5d5e4", name: "NORDIC HAM CURL", warmupSets: 0, workingSets: 3, reps: "6-8", rpe: "8", rest: "1-2 MIN", notes: "BEND FORWARD AT HIPS DURING THE CONCENTRIC AND MINIMIZE CONTRIBUTION FROM HANDS" },
        { id: "w5d5e5", name: "DUMBBELL SHRUG", warmupSets: 0, workingSets: 3, reps: "20-25", rpe: "10", rest: "1-2 MIN", notes: "FEEL A STRETCH ON THE TRAPS AT THE BOTTOM, SQUEEZE HARD AT THE TOP" },
      ],
    },
    {
      id: "w5d6",
      name: "Day 6 — Supplemental A (Arms)",
      source: "arms",
      note: "Take the last set of each exercise to failure.",
      exercises: [
        { id: "w5d6e1", name: "Dumbbell Concentration Curl", workingSets: 4, reps: "8-10", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Elbow pinned against thigh, rotating grip (supinate through the concentric)." },
        { id: "w5d6e2", name: "Standing EZ Bar Curl (Descending ROM)", workingSets: 2, reps: "10+5+5", rpe: "9", rest: "1.5", notes: "10 reps full ROM, 5 reps top end ROM, 5 reps bottom end ROM." },
        { id: "w5d6e3", name: "Weighted Dip (Close Grip)", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "8", rest: "2.0", notes: "More upright posture, mind-muscle connection with the triceps." },
        { id: "w5d6e4", name: "1-Arm Overhead Cable Extension", workingSets: 2, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Keep your elbow locked into place and tucked in." },
        { id: "w5d6e5", name: "Reverse Grip Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    ],
  },
  {
    id: "w6",
    name: "Week 6",
    days: [
    {
      id: "w6d1",
      name: "Day 1 — Lower #1",
      source: "powerbuilding",
      exercises: [
        { id: "w6d1e1", name: "DEADLIFT", warmupSets: 4, workingSets: 3, reps: "4", percent1RM: "80%", rest: "3-5 MIN", notes: "BRACE YOUR LATS, CHEST TALL, PULL THE SLACK OUT OF THE BAR BEFORE LIFTING" },
        { id: "w6d1e2", name: "SUMO BOX SQUAT OR PAUSE HIGH-BAR SQUAT", warmupSets: 2, workingSets: 2, reps: "8", rpe: "5", rest: "2-3 MIN", notes: "IF YOU SQUAT HIGH-BAR, DO SUMO BOX SQUAT. IF YOU SQUAT LOW-BAR, DO PAUSE HIGH-BAR (2 SEC PAUSE)" },
        { id: "w6d1e3", name: "LEG CURL", warmupSets: 1, workingSets: 3, reps: "6-8", rpe: "7", rest: "1-2 MIN", notes: "DO LYING LEG CURL MACHINE OR NORDIC HAM CURL IF NO MACHINE ACCESS" },
        { id: "w6d1e4", name: "STANDING CALF RAISE", warmupSets: 1, workingSets: 3, reps: "8-10", rpe: "7", rest: "1-2 MIN", notes: "1-2 SECOND PAUSE AT THE BOTTOM OF EACH REP, FULL SQUEEZE AT THE TOP" },
        { id: "w6d1e5", name: "HANGING LEG RAISE", warmupSets: 0, workingSets: 3, reps: "10-12", rpe: "8", rest: "1-2 MIN", notes: "KNEES TO CHEST, CONTROLLED REPS, STRAIGHTEN LEGS MORE TO INCREASE DIFFICULTY" },
      ],
    },
    {
      id: "w6d2",
      name: "Day 2 — Upper #1",
      source: "powerbuilding",
      exercises: [
        { id: "w6d2e1", name: "BARBELL BENCH PRESS", warmupSets: 3, workingSets: 2, reps: "7", percent1RM: "77.5%", rest: "3-4 MIN", notes: "SET UP A COMFORTABLE ARCH, SLIGHT PAUSE ON THE CHEST, EXPLODE UP" },
        { id: "w6d2e2", name: "CHIN-UP", warmupSets: 1, workingSets: 2, reps: "8-10", rpe: "7", rest: "2-3 MIN", notes: "UNDERHAND GRIP, PULL YOUR CHEST TO THE BAR, ADD WEIGHT IF NEEDED TO HIT RPE" },
        { id: "w6d2e3", name: "OVERHEAD PRESS", warmupSets: 2, workingSets: 3, reps: "4", percent1RM: "82.5%", rest: "1-2 MIN", notes: "SQUEEZE YOUR GLUTES TO KEEP YOUR TORSO UPRIGHT, PRESS UP AND SLIGHTLY BACK" },
        { id: "w6d2e4", name: "CHEST-SUPPORTED DUMBBELL ROW", warmupSets: 1, workingSets: 2, reps: "12-15", rpe: "7", rest: "3-4 MIN", notes: "LIE ON AN INCLINE BENCH AND DO ROWS - PULL WITH LATS!" },
        { id: "w6d2e5", name: "A1: FACE PULL", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "8", rest: "30SEC", notes: "CAN USE CABLE/ROPE OR BAND, RETRACT YOUR SHOULDER BLADES AS YOU PULL" },
        { id: "w6d2e6", name: "A2: DUMBBELL LATERAL RAISE", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "8", rest: "30SEC", notes: "ARC THE DUMBBELL OUT, MIND-MUSCLE CONNECTION WITH MIDDLE FIBERS" },
        { id: "w6d2e7", name: "B1: CONCENTRATION BICEP CURL", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "8", rest: "30SEC", notes: "PIN YOUR ELBOW AGAINST YOUR UPPER LEG OR THE BACK OF A BENCH" },
        { id: "w6d2e8", name: "B2: TRICEPS PRESSDOWN", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "8", rest: "30SEC", notes: "CAN DO WITH CABLES OR BANDS, SQUEEZE TRICEPS TO MOVE THE WEIGHT" },
      ],
    },
    {
      id: "w6d3",
      name: "Day 3 — Arm Day",
      source: "arms",
      note: "Take the last set of each exercise except close grip bench press to failure.",
      exercises: [
        { id: "w6d3e1", name: "Close Grip Bench Press", workingSets: 4, reps: "4-6", tempo: "2.1.1.1", rpe: "8", rest: "3.0", notes: "Shoulder width grip. Touch bar to chest with a silent pause." },
        { id: "w6d3e2", name: "Bayesian Cable Curl", workingSets: 2, reps: "12-15", tempo: "2.0.2.0", rpe: "7", rest: "1.0", notes: "Pre-activation. Smooth, controlled reps — slight pump with light weight." },
        { id: "w6d3e3", name: "Standing EZ Bar Curl", workingSets: 4, reps: "4-6", tempo: "2.0.1.0", rpe: "9", rest: "3.0", notes: "2 sets wider grip, 2 closer. Last set to failure, 1-2 cheat reps at end." },
        { id: "w6d3e4", name: "Dumbbell Preacher Hammer Curl", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, hammer grip in the middle of the dumbbell." },
        { id: "w6d3e5", name: "Tricep Pressdown", workingSets: 4, reps: "10-12", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Bar attachment. 2 sets wide, 2 narrow. Keep elbows locked." },
        { id: "w6d3e6", name: "Overhead Rope Tricep Extension", workingSets: 2, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, press the rope apart at the top end ROM." },
        { id: "w6d3e7", name: "Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    {
      id: "w6d4",
      name: "Day 4 — Lower # 2",
      source: "powerbuilding",
      exercises: [
        { id: "w6d4e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 1, reps: "1", percent1RM: "90-95%", rpe: "9", rest: "4-5 MIN", notes: "ONLY HEAVY SET THIS WEEK! PERFECT TECHNIQUE!" },
        { id: "w6d4e2", name: "LOW-BAR BACK SQUAT", warmupSets: 0, workingSets: 2, reps: "7", percent1RM: "75%", rest: "3-4 MIN", notes: "SIT BACK AND DOWN, KEEP YOUR UPPER BACK TIGHT TO THE BAR" },
        { id: "w6d4e3", name: "SNATCH-GRIP ROMANIAN DEADLIFT", warmupSets: 2, workingSets: 2, reps: "10", rpe: "6", rest: "2-3 MIN", notes: "WIDE GRIP, MIND-MUSCLE CONNECTION WITH HAMSTRINGS" },
        { id: "w6d4e4", name: "LEG EXTENSION", warmupSets: 1, workingSets: 2, reps: "12-15", rpe: "8", rest: "1-2 MIN", notes: "USE BANDS IF NO MACHINE ACCESS, MIND-MUSCLE CONNECTION WITH QUADS" },
        { id: "w6d4e5", name: "STANDING CALF RAISE", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "8", rest: "1-2 MIN", notes: "EMPHASIZE THE MIND-MUSCLE CONNECTION" },
        { id: "w6d4e6", name: "BANDED LATERAL WALK OR HIP ABDUCTION", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "8", rest: "1-2 MIN", notes: "POINT TOES SLIGHTLY OUTWARD, MIND-MUSCLE CONNECTION WITH GLUTES" },
        { id: "w6d4e7", name: "V SIT-UP", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "8", rest: "1-2 MIN", notes: "THINK ABOUT SQUEEZING YOUR UPPER AND LOWER ABS TOGETHER" },
        { id: "w6d4e8", name: "NECK FLEXION/EXTENSION (OPTIONAL)", warmupSets: 1, workingSets: 3, reps: "12/12", rpe: "8", rest: "1-2 MIN", notes: "12 REPS FLEXION (FRONT OF NECK), 12 REPS EXTENSION (BACK OF NECK)" },
      ],
    },
    {
      id: "w6d5",
      name: "Day 5 — Upper #2",
      source: "powerbuilding",
      exercises: [
        { id: "w6d5e1", name: "BARBELL FLOOR PRESS", warmupSets: 2, workingSets: 3, reps: "8", rpe: "7", rest: "2-3 MIN", notes: "CONTROL THE ECCENTRIC (DON'T LET YOUR ELBOWS SLAM INTO THE GROUND), BE EXPLOSIVE ON THE WAY UP" },
        { id: "w6d5e2", name: "PENDLAY ROW", warmupSets: 1, workingSets: 2, reps: "10", rpe: "7", rest: "2-3 MIN", notes: "BE MINDFUL OF LOWER BACK FATIGUE. STAY LIGHT, MINIMIZE CHEATING" },
        { id: "w6d5e3", name: "WEIGHTED DIP", warmupSets: 2, workingSets: 3, reps: "6", rpe: "7", rest: "2-3 MIN", notes: "DO INCLINE DUMBBELL PRESS IF NO ACCESS TO DIP HANDLES" },
        { id: "w6d5e4", name: "NEUTRAL GRIP PULL-UP", warmupSets: 1, workingSets: 2, reps: "10", rpe: "7", rest: "2-3 MIN", notes: "AVOID FAILURE, FOCUS ON GOOD TECHNIQUE AND MAINTAINING CONSISTENT TEMPO" },
        { id: "w6d5e5", name: "A1. INCLINE SHRUG", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "8", rest: "30SEC", notes: "LIE FACE DOWN AGAINST AN INCLINE BENCH AND DO SHRUGS - FULL ROM AND SQUEEZE!" },
        { id: "w6d5e6", name: "A2. UPRIGHT ROW", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "8", rest: "30SEC", notes: "CAN USE CABLES/ROPE, BANDS OR DUMBBELLS. STOP ROM ONCE ELBOWS REACH SHOULDER HEIGHT." },
        { id: "w6d5e7", name: "B1: BARBELL OR EZ BAR CURL", warmupSets: 0, workingSets: 2, reps: "12-15", rpe: "8", rest: "30SEC", notes: "FOCUS ON THE MIND-MUSCLE CONNECTION" },
        { id: "w6d5e8", name: "B2. SKULL CRUSHER", warmupSets: 0, workingSets: 2, reps: "8-10", rpe: "8", rest: "30SEC", notes: "BARBELL OR EZ BAR, DO THESE ON A BENCH, CONSTANT TENSION ON TRICEPS" },
      ],
    },
    {
      id: "w6d6",
      name: "Day 6 — Supplemental A (Arms)",
      source: "arms",
      note: "Take the last set of each exercise to failure.",
      exercises: [
        { id: "w6d6e1", name: "Dumbbell Concentration Curl", workingSets: 4, reps: "8-10", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Elbow pinned against thigh, rotating grip (supinate through the concentric)." },
        { id: "w6d6e2", name: "Standing EZ Bar Curl (Descending ROM)", workingSets: 2, reps: "10+5+5", rpe: "9", rest: "1.5", notes: "10 reps full ROM, 5 reps top end ROM, 5 reps bottom end ROM." },
        { id: "w6d6e3", name: "Weighted Dip (Close Grip)", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "8", rest: "2.0", notes: "More upright posture, mind-muscle connection with the triceps." },
        { id: "w6d6e4", name: "1-Arm Overhead Cable Extension", workingSets: 2, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Keep your elbow locked into place and tucked in." },
        { id: "w6d6e5", name: "Reverse Grip Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    ],
  },
  {
    id: "w7",
    name: "Week 7",
    days: [
    {
      id: "w7d1",
      name: "Day 1 — Full Body 1: Squat, Ohp",
      source: "powerbuilding",
      exercises: [
        { id: "w7d1e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 1, reps: "3", percent1RM: "85-90%", rpe: "8.5", rest: "4-5 MIN", notes: "TRY TO ADD SOME WEIGHT FROM WEEK 5 OR IMPROVE BAR SPEED AT SAME WEIGHT" },
        { id: "w7d1e2", name: "BACK SQUAT", warmupSets: 0, workingSets: 2, reps: "2", percent1RM: "85%", rest: "3-4 MIN", notes: "BE MINDFUL OF TECHNIQUE. FOCUS ON DRIVING YOUR BACK INTO THE BAR." },
        { id: "w7d1e3", name: "OVERHEAD PRESS", warmupSets: 2, workingSets: 4, reps: "8", percent1RM: "70%", rest: "2-3 MIN", notes: "RESET EACH REP (DON'T TOUCH-AND-PRESS)" },
        { id: "w7d1e4", name: "GLUTE HAM RAISE", warmupSets: 1, workingSets: 2, reps: "8-10", rpe: "8", rest: "1-2 MIN", notes: "KEEP YOUR HIPS STRAIGHT, DO NORDIC HAM CURLS IF NO GHR MACHINE" },
        { id: "w7d1e5", name: "HELMS ROW", warmupSets: 1, workingSets: 2, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "STRICT FORM. DRIVE ELBOWS OUT AND BACK AT 45 DEGREE ANGLE" },
        { id: "w7d1e6", name: "HAMMER CURL", warmupSets: 0, workingSets: 2, reps: "20-25", rpe: "10", rest: "1-2 MIN", notes: "KEEP ELBOWS LOCKED IN PLACE, SQUEEZE THE DUMBBELL HANDLE HARD!" },
      ],
    },
    {
      id: "w7d2",
      name: "Day 2 — Full Body 2: Deadlift, Bench Press",
      source: "powerbuilding",
      exercises: [
        { id: "w7d2e1", name: "PAUSE DEADLIFT", warmupSets: 4, workingSets: 4, reps: "2", percent1RM: "75%", rest: "3-4 MIN", notes: "3 SECOND PAUSE RIGHT AFTER THE PLATES COME OFF THE GROUND" },
        { id: "w7d2e2", name: "BARBELL BENCH PRESS", warmupSets: 4, workingSets: 1, reps: "3", percent1RM: "85-90%", rpe: "9", rest: "4-5 MIN", notes: "TOP SET. LEAVE 1 REP IN THE TANK. AIM FOR NEAR 3 REP PR." },
        { id: "w7d2e3", name: "BARBELL BENCH PRESS", warmupSets: 0, workingSets: 2, reps: "4", percent1RM: "80%", rest: "3-4 MIN", notes: "FOCUS ON TECHNIQUE. PRESS THE BAR BACK AND UP WITH EXPLOSIVE FORCE" },
        { id: "w7d2e4", name: "HIP ABDUCTION", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "MACHINE, BAND OR WEIGHTED, 1 SECOND ISOMETRIC HOLD AT THE TOP OF EACH REP" },
        { id: "w7d2e5", name: "WEIGHTED PULL-UP", warmupSets: 1, workingSets: 3, reps: "3-5", rpe: "7", rest: "3-4 MIN", notes: "1.5X SHOULDER WIDTH GRIP, PULL YOUR CHEST TO THE BAR" },
        { id: "w7d2e6", name: "FLOOR SKULL CRUSHER", warmupSets: 1, workingSets: 3, reps: "10-12", rpe: "8", rest: "1-2 MIN", notes: "ARC THE BAR BACK BEHIND YOUR HEAD, SOFT TOUCH ON THE FLOOR BEHIND YOU" },
        { id: "w7d2e7", name: "STANDING CALF RAISE", warmupSets: 1, workingSets: 3, reps: "8", rpe: "9", rest: "1-2 MIN", notes: "1-2 SECOND PAUSE AT THE BOTTOM OF EACH REP, FULL ROM" },
      ],
    },
    {
      id: "w7d3",
      name: "Day 3 — Arm Day",
      source: "arms",
      note: "Take the last set of each exercise except close grip bench press to failure.",
      exercises: [
        { id: "w7d3e1", name: "Close Grip Bench Press", workingSets: 4, reps: "4-6", tempo: "2.1.1.1", rpe: "8", rest: "3.0", notes: "Shoulder width grip. Touch bar to chest with a silent pause." },
        { id: "w7d3e2", name: "Bayesian Cable Curl", workingSets: 2, reps: "12-15", tempo: "2.0.2.0", rpe: "7", rest: "1.0", notes: "Pre-activation. Smooth, controlled reps — slight pump with light weight." },
        { id: "w7d3e3", name: "Standing EZ Bar Curl", workingSets: 4, reps: "4-6", tempo: "2.0.1.0", rpe: "9", rest: "3.0", notes: "2 sets wider grip, 2 closer. Last set to failure, 1-2 cheat reps at end." },
        { id: "w7d3e4", name: "Dumbbell Preacher Hammer Curl", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, hammer grip in the middle of the dumbbell." },
        { id: "w7d3e5", name: "Tricep Pressdown", workingSets: 4, reps: "10-12", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Bar attachment. 2 sets wide, 2 narrow. Keep elbows locked." },
        { id: "w7d3e6", name: "Overhead Rope Tricep Extension", workingSets: 2, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, press the rope apart at the top end ROM." },
        { id: "w7d3e7", name: "Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    {
      id: "w7d4",
      name: "Day 4 — Full Body 3: Squat, Dip",
      source: "powerbuilding",
      exercises: [
        { id: "w7d4e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 4, reps: "6", percent1RM: "77.5%", rest: "3-4 MIN", notes: "MAINTAIN TIGHT PRESSURE IN YOUR UPPER BACK AGAINST THE BAR" },
        { id: "w7d4e2", name: "WEIGHTED DIP", warmupSets: 2, workingSets: 3, reps: "8", rpe: "8", rest: "2-3 MIN", notes: "DO DUMBBELL FLOOR PRESS IF NO ACCESS TO DIP HANDLES" },
        { id: "w7d4e3", name: "HANGING LEG RAISE", warmupSets: 0, workingSets: 3, reps: "10-12", rpe: "9", rest: "1-2 MIN", notes: "KNEES TO CHEST, CONTROLLED REPS, STRAIGHTEN LEGS MORE TO INCREASE DIFFICULTY" },
        { id: "w7d4e4", name: "LAT PULL-OVER", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "CAN USE A DB, CABLE/ROPE OR BAND, STRETCH AND SQUEEZE LATS!" },
        { id: "w7d4e5", name: "INCLINE DUMBBELL CURL", warmupSets: 1, workingSets: 2, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "DO EACH ARM ONE AT A TIME RATHER THAN ALTERNATING, START WITH YOUR WEAK ARM" },
        { id: "w7d4e6", name: "FACE PULL", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "CAN USE CABLE/ROPE OR BAND, RETRACT YOUR SHOULDER BLADES AS YOU PULL" },
      ],
    },
    {
      id: "w7d5",
      name: "Day 5 — Full Body 4: Deadlift, Bench Press",
      source: "powerbuilding",
      exercises: [
        { id: "w7d5e1", name: "DEADLIFT", warmupSets: 4, workingSets: 1, reps: "3", percent1RM: "85-90%", rpe: "8.5", rest: "4-5 MIN", notes: "WORK UP TO A HEAVY TRIPLE WITH A LOAD THAT HITS RPE 8-9" },
        { id: "w7d5e2", name: "PAUSE BARBELL BENCH PRESS", warmupSets: 3, workingSets: 4, reps: "6", percent1RM: "75%", rest: "2-3 MIN", notes: "2-3 SECOND PAUSE ON THE CHEST" },
        { id: "w7d5e3", name: "CHEST-SUPPORTED T-BAR ROW OR PENDLAY ROW", warmupSets: 1, workingSets: 3, reps: "10", rpe: "7", rest: "2-3 MIN", notes: "BE MINDFUL OF LOWER BACK FATIGUE. STAY LIGHT, MINIMIZE CHEATING" },
        { id: "w7d5e4", name: "NORDIC HAM CURL", warmupSets: 0, workingSets: 3, reps: "6-8", rpe: "8", rest: "1-2 MIN", notes: "BEND FORWARD AT HIPS DURING THE CONCENTRIC AND MINIMIZE CONTRIBUTION FROM HANDS" },
        { id: "w7d5e5", name: "DUMBBELL SHRUG", warmupSets: 0, workingSets: 3, reps: "20-25", rpe: "9", rest: "1-2 MIN", notes: "FEEL A STRETCH ON THE TRAPS AT THE BOTTOM, SQUEEZE HARD AT THE TOP" },
      ],
    },
    {
      id: "w7d6",
      name: "Day 6 — Supplemental A (Arms)",
      source: "arms",
      note: "Take the last set of each exercise to failure.",
      exercises: [
        { id: "w7d6e1", name: "Dumbbell Concentration Curl", workingSets: 4, reps: "8-10", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Elbow pinned against thigh, rotating grip (supinate through the concentric)." },
        { id: "w7d6e2", name: "Standing EZ Bar Curl (Descending ROM)", workingSets: 2, reps: "10+5+5", rpe: "9", rest: "1.5", notes: "10 reps full ROM, 5 reps top end ROM, 5 reps bottom end ROM." },
        { id: "w7d6e3", name: "Weighted Dip (Close Grip)", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "8", rest: "2.0", notes: "More upright posture, mind-muscle connection with the triceps." },
        { id: "w7d6e4", name: "1-Arm Overhead Cable Extension", workingSets: 2, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Keep your elbow locked into place and tucked in." },
        { id: "w7d6e5", name: "Reverse Grip Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    ],
  },
  {
    id: "w8",
    name: "Week 8",
    days: [
    {
      id: "w8d1",
      name: "Day 1 — Lower #1",
      source: "powerbuilding",
      exercises: [
        { id: "w8d1e1", name: "DEADLIFT", warmupSets: 4, workingSets: 3, reps: "5", percent1RM: "80%", rest: "3-5 MIN", notes: "BRACE YOUR LATS, CHEST TALL, PULL THE SLACK OUT OF THE BAR BEFORE LIFTING" },
        { id: "w8d1e2", name: "SUMO BOX SQUAT OR PAUSE HIGH-BAR SQUAT", warmupSets: 2, workingSets: 2, reps: "8", rpe: "7", rest: "2-3 MIN", notes: "IF YOU SQUAT HIGH-BAR, DO SUMO BOX SQUAT. IF YOU SQUAT LOW-BAR, DO PAUSE HIGH-BAR (2 SEC PAUSE)" },
        { id: "w8d1e3", name: "LEG CURL", warmupSets: 1, workingSets: 3, reps: "6-8", rpe: "8", rest: "1-2 MIN", notes: "DO LYING LEG CURL MACHINE OR NORDIC HAM CURL IF NO MACHINE ACCESS" },
        { id: "w8d1e4", name: "STANDING CALF RAISE", warmupSets: 1, workingSets: 3, reps: "8-10", rpe: "9", rest: "1-2 MIN", notes: "1-2 SECOND PAUSE AT THE BOTTOM OF EACH REP, FULL SQUEEZE AT THE TOP" },
        { id: "w8d1e5", name: "HANGING LEG RAISE", warmupSets: 0, workingSets: 3, reps: "10-12", rpe: "8", rest: "1-2 MIN", notes: "KNEES TO CHEST, CONTROLLED REPS, STRAIGHTEN LEGS MORE TO INCREASE DIFFICULTY" },
      ],
    },
    {
      id: "w8d2",
      name: "Day 2 — Upper #1",
      source: "powerbuilding",
      exercises: [
        { id: "w8d2e1", name: "FLAT-BACK BENCH PRESS", warmupSets: 3, workingSets: 3, reps: "10", rpe: "7", rest: "3-4 MIN", notes: "SHOULDER BLADES STILL RETRACTED AND DEPRESSED. SLIGHT ARCH IN UPPER BACK. MINIMIZE LEG DRIVE." },
        { id: "w8d2e2", name: "CHIN-UP", warmupSets: 1, workingSets: 3, reps: "8-10", rpe: "8", rest: "2-3 MIN", notes: "UNDERHAND GRIP, PULL YOUR CHEST TO THE BAR, ADD WEIGHT IF NEEDED TO HIT RPE" },
        { id: "w8d2e3", name: "OVERHEAD PRESS / PUSH PRESS", warmupSets: 2, workingSets: 3, reps: "3/3", percent1RM: "82.5%", rest: "1-2 MIN", notes: "FIRST 3 REPS STRICT MILITARY PRESS (NO LEG DRIVE), LAST 3 REPS PUSH PRESS (USE LEG DRIVE)" },
        { id: "w8d2e4", name: "CHEST-SUPPORTED DUMBBELL ROW", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "3-4 MIN", notes: "LIE ON AN INCLINE BENCH AND DO ROWS - PULL WITH LATS!" },
        { id: "w8d2e5", name: "A1: FACE PULL", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "30SEC", notes: "CAN USE CABLE/ROPE OR BAND, RETRACT YOUR SHOULDER BLADES AS YOU PULL" },
        { id: "w8d2e6", name: "A2: DUMBBELL LATERAL RAISE", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "30SEC", notes: "ARC THE DUMBBELL OUT, MIND-MUSCLE CONNECTION WITH MIDDLE FIBERS" },
        { id: "w8d2e7", name: "B1: CONCENTRATION BICEP CURL", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "30SEC", notes: "PIN YOUR ELBOW AGAINST YOUR UPPER LEG OR THE BACK OF A BENCH" },
        { id: "w8d2e8", name: "B2: TRICEPS PRESSDOWN", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "30SEC", notes: "CAN DO WITH CABLES OR BANDS, SQUEEZE TRICEPS TO MOVE THE WEIGHT" },
      ],
    },
    {
      id: "w8d3",
      name: "Day 3 — Arm Day",
      source: "arms",
      note: "Take the last set of each exercise except close grip bench press to failure.",
      exercises: [
        { id: "w8d3e1", name: "Close Grip Bench Press", workingSets: 4, reps: "4-6", tempo: "2.1.1.1", rpe: "8", rest: "3.0", notes: "Shoulder width grip. Touch bar to chest with a silent pause." },
        { id: "w8d3e2", name: "Bayesian Cable Curl", workingSets: 2, reps: "12-15", tempo: "2.0.2.0", rpe: "7", rest: "1.0", notes: "Pre-activation. Smooth, controlled reps — slight pump with light weight." },
        { id: "w8d3e3", name: "Standing EZ Bar Curl", workingSets: 4, reps: "4-6", tempo: "2.0.1.0", rpe: "9", rest: "3.0", notes: "2 sets wider grip, 2 closer. Last set to failure, 1-2 cheat reps at end." },
        { id: "w8d3e4", name: "Dumbbell Preacher Hammer Curl", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, hammer grip in the middle of the dumbbell." },
        { id: "w8d3e5", name: "Tricep Pressdown", workingSets: 4, reps: "10-12", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Bar attachment. 2 sets wide, 2 narrow. Keep elbows locked." },
        { id: "w8d3e6", name: "Overhead Rope Tricep Extension", workingSets: 2, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, press the rope apart at the top end ROM." },
        { id: "w8d3e7", name: "Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    {
      id: "w8d4",
      name: "Day 4 — Lower #2",
      source: "powerbuilding",
      exercises: [
        { id: "w8d4e1", name: "LOW-BAR BACK SQUAT", warmupSets: 4, workingSets: 3, reps: "7", percent1RM: "75%", rest: "3-4 MIN", notes: "SIT BACK AND DOWN, KEEP YOUR UPPER BACK TIGHT TO THE BAR" },
        { id: "w8d4e2", name: "3\" BLOCK PULL", warmupSets: 3, workingSets: 2, reps: "4", rpe: "8", rest: "4-5 MIN", notes: "DO BLOCK PULLS FROM A 3\" BLOCK (CAN USE 25LB + 10LB BUMPERS AS BLOCKS)" },
        { id: "w8d4e3", name: "LEG EXTENSION", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "USE BANDS IF NO MACHINE ACCESS, MIND-MUSCLE CONNECTION WITH QUADS" },
        { id: "w8d4e4", name: "STANDING CALF RAISE", warmupSets: 0, workingSets: 4, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "EMPHASIZE THE MIND-MUSCLE CONNECTION" },
        { id: "w8d4e5", name: "BANDED LATERAL WALK OR HIP ABDUCTION", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "POINT TOES SLIGHTLY OUTWARD, MIND-MUSCLE CONNECTION WITH GLUTES" },
        { id: "w8d4e6", name: "V SIT-UP", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "THINK ABOUT SQUEEZING YOUR UPPER AND LOWER ABS TOGETHER" },
        { id: "w8d4e7", name: "NECK FLEXION/EXTENSION (OPTIONAL)", warmupSets: 1, workingSets: 3, reps: "12/12", rpe: "8", rest: "1-2 MIN", notes: "12 REPS FLEXION (FRONT OF NECK), 12 REPS EXTENSION (BACK OF NECK)" },
      ],
    },
    {
      id: "w8d5",
      name: "Day 5 — Upper #2",
      source: "powerbuilding",
      exercises: [
        { id: "w8d5e1", name: "DUMBBELL INCLINE PRESS", warmupSets: 2, workingSets: 3, reps: "8", rpe: "8", rest: "2-3 MIN", notes: "45° INCLINE, KEEP SHOULDER BLADES RETRACTED AND DEPRESSED" },
        { id: "w8d5e2", name: "PENDLAY ROW", warmupSets: 1, workingSets: 3, reps: "10", rpe: "7", rest: "2-3 MIN", notes: "BE MINDFUL OF LOWER BACK FATIGUE. STAY LIGHT, MINIMIZE CHEATING" },
        { id: "w8d5e3", name: "WEIGHTED DIP", warmupSets: 2, workingSets: 3, reps: "6", rpe: "7", rest: "2-3 MIN", notes: "DO DUMBBELL FLOOR PRESS IF NO ACCESS TO DIP HANDLES" },
        { id: "w8d5e4", name: "ECCENTRIC-ACCENTUATED PULL-UP", warmupSets: 1, workingSets: 2, reps: "AMRAP", rpe: "10", rest: "2-3 MIN", notes: "3 SECOND NEGATIVE ON EVERY REP, MAINTAIN CONTROLLED FORM FOR ALL REPS" },
        { id: "w8d5e5", name: "A1. INCLINE SHRUG", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "9", rest: "30SEC", notes: "LIE FACE DOWN AGAINST AN INCLINE BENCH AND DO SHRUGS - FULL ROM AND SQUEEZE!" },
        { id: "w8d5e6", name: "A2. BENT OVER REVERSE DUMBBELL FLYE", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "9", rest: "30SEC", notes: "MIND-MUSCLE CONNECTION WITH REAR DELTS, SWEEP THE WEIGHT OUT" },
        { id: "w8d5e7", name: "B1: BARBELL OR EZ BAR CURL", warmupSets: 0, workingSets: 3, reps: "12-15", rpe: "9", rest: "30SEC", notes: "FOCUS ON THE MIND-MUSCLE CONNECTION" },
        { id: "w8d5e8", name: "B2. SKULL CRUSHER", warmupSets: 0, workingSets: 3, reps: "8-10", rpe: "9", rest: "30SEC", notes: "BARBELL OR EZ BAR, DO THESE ON A BENCH, CONSTANT TENSION ON TRICEPS" },
      ],
    },
    {
      id: "w8d6",
      name: "Day 6 — Supplemental A (Arms)",
      source: "arms",
      note: "Take the last set of each exercise to failure.",
      exercises: [
        { id: "w8d6e1", name: "Dumbbell Concentration Curl", workingSets: 4, reps: "8-10", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Elbow pinned against thigh, rotating grip (supinate through the concentric)." },
        { id: "w8d6e2", name: "Standing EZ Bar Curl (Descending ROM)", workingSets: 2, reps: "10+5+5", rpe: "9", rest: "1.5", notes: "10 reps full ROM, 5 reps top end ROM, 5 reps bottom end ROM." },
        { id: "w8d6e3", name: "Weighted Dip (Close Grip)", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "8", rest: "2.0", notes: "More upright posture, mind-muscle connection with the triceps." },
        { id: "w8d6e4", name: "1-Arm Overhead Cable Extension", workingSets: 2, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Keep your elbow locked into place and tucked in." },
        { id: "w8d6e5", name: "Reverse Grip Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    ],
  },
  {
    id: "w9",
    name: "Week 9",
    days: [
    {
      id: "w9d1",
      name: "Day 1 — Full Body 1: Squat, Ohp",
      source: "powerbuilding",
      exercises: [
        { id: "w9d1e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 1, reps: "2", percent1RM: "87.5-92.5%", rpe: "8.5", rest: "4-5 MIN", notes: "TOP SET. LEAVE 1 (MAYBE 2) REPS IN THE TANK. AIM FOR NEAR 2 REP PR." },
        { id: "w9d1e2", name: "SQUAT WALK-OUT (DO NOT SQUAT)", warmupSets: 0, workingSets: 1, reps: "10-SEC", percent1RM: "100%", rpe: "NO REPS", rest: "4-5 MIN", notes: "DO NOT SQUAT. WALK THE WEIGHT OUT, HOLD AND WALK BACK IN. SET THE SAFETY PINS HIGH AND HAVE A SPOTTER." },
        { id: "w9d1e3", name: "OVERHEAD PRESS", warmupSets: 2, workingSets: 3, reps: "6", percent1RM: "80%", rest: "2-3 MIN", notes: "RESET EACH REP (DON'T TOUCH-AND-PRESS)" },
        { id: "w9d1e4", name: "GLUTE HAM RAISE", warmupSets: 1, workingSets: 2, reps: "8-10", rpe: "7", rest: "1-2 MIN", notes: "KEEP YOUR HIPS STRAIGHT, DO NORDIC HAM CURLS IF NO GHR MACHINE" },
        { id: "w9d1e5", name: "HELMS ROW", warmupSets: 1, workingSets: 2, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "STRICT FORM. DRIVE ELBOWS OUT AND BACK AT 45 DEGREE ANGLE" },
        { id: "w9d1e6", name: "HAMMER CURL", warmupSets: 0, workingSets: 2, reps: "20-25", rpe: "10", rest: "1-2 MIN", notes: "KEEP ELBOWS LOCKED IN PLACE, SQUEEZE THE DUMBBELL HANDLE HARD!" },
      ],
    },
    {
      id: "w9d2",
      name: "Day 2 — Full Body 2: Deadlift, Bench Press",
      source: "powerbuilding",
      exercises: [
        { id: "w9d2e1", name: "DEADLIFT", warmupSets: 4, workingSets: 3, reps: "4", percent1RM: "80%", rest: "3-5 MIN", notes: "SEMI-DELOAD. FOCUS ON TECHNIQUE AND BAR SPEED LEADING INTO MAX WEEK." },
        { id: "w9d2e2", name: "BARBELL BENCH PRESS", warmupSets: 4, workingSets: 1, reps: "2", percent1RM: "87.5-92.5%", rpe: "9", rest: "4-5 MIN", notes: "TOP SET. AIM FOR A NEAR 2 REP PR" },
        { id: "w9d2e3", name: "BARBELL BENCH PRESS", warmupSets: 0, workingSets: 2, reps: "2", percent1RM: "87.5%", rest: "3-4 MIN", notes: "FOCUS ON TECHNIQUE. PRESS THE BAR BACK AND UP WITH EXPLOSIVE FORCE" },
        { id: "w9d2e4", name: "HIP ABDUCTION", warmupSets: 0, workingSets: 3, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "MACHINE, BAND OR WEIGHTED, 1 SECOND ISOMETRIC HOLD AT THE TOP OF EACH REP" },
        { id: "w9d2e5", name: "WEIGHTED PULL-UP", warmupSets: 1, workingSets: 3, reps: "3-5", rpe: "7", rest: "2-3 MIN", notes: "1.5X SHOULDER WIDTH GRIP, PULL YOUR CHEST TO THE BAR" },
        { id: "w9d2e6", name: "FLOOR SKULL CRUSHER", warmupSets: 1, workingSets: 3, reps: "10-12", rpe: "8", rest: "1-2 MIN", notes: "ARC THE BAR BACK BEHIND YOUR HEAD, SOFT TOUCH ON THE FLOOR BEHIND YOU" },
        { id: "w9d2e7", name: "STANDING CALF RAISE", warmupSets: 1, workingSets: 3, reps: "8", rpe: "9", rest: "1-2 MIN", notes: "1-2 SECOND PAUSE AT THE BOTTOM OF EACH REP, FULL ROM" },
      ],
    },
    {
      id: "w9d3",
      name: "Day 3 — Arm Day",
      source: "arms",
      note: "Take the last set of each exercise except close grip bench press to failure.",
      exercises: [
        { id: "w9d3e1", name: "Close Grip Bench Press", workingSets: 4, reps: "4-6", tempo: "2.1.1.1", rpe: "8", rest: "3.0", notes: "Shoulder width grip. Touch bar to chest with a silent pause." },
        { id: "w9d3e2", name: "Bayesian Cable Curl", workingSets: 2, reps: "12-15", tempo: "2.0.2.0", rpe: "7", rest: "1.0", notes: "Pre-activation. Smooth, controlled reps — slight pump with light weight." },
        { id: "w9d3e3", name: "Standing EZ Bar Curl", workingSets: 4, reps: "4-6", tempo: "2.0.1.0", rpe: "9", rest: "3.0", notes: "2 sets wider grip, 2 closer. Last set to failure, 1-2 cheat reps at end." },
        { id: "w9d3e4", name: "Dumbbell Preacher Hammer Curl", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, hammer grip in the middle of the dumbbell." },
        { id: "w9d3e5", name: "Tricep Pressdown", workingSets: 4, reps: "10-12", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Bar attachment. 2 sets wide, 2 narrow. Keep elbows locked." },
        { id: "w9d3e6", name: "Overhead Rope Tricep Extension", workingSets: 2, reps: "12-15", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Both arms at once, press the rope apart at the top end ROM." },
        { id: "w9d3e7", name: "Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    {
      id: "w9d4",
      name: "Day 4 — Full Body 3: Squat, Dip",
      source: "powerbuilding",
      exercises: [
        { id: "w9d4e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 3, reps: "4", percent1RM: "82.5%", rest: "3-4 MIN", notes: "MAINTAIN TIGHT PRESSURE IN YOUR UPPER BACK AGAINST THE BAR" },
        { id: "w9d4e2", name: "WEIGHTED DIP", warmupSets: 2, workingSets: 3, reps: "8", rpe: "8", rest: "2-3 MIN", notes: "DO DUMBBELL FLOOR PRESS IF NO ACCESS TO DIP HANDLES" },
        { id: "w9d4e3", name: "HANGING LEG RAISE", warmupSets: 0, workingSets: 3, reps: "10-12", rpe: "9", rest: "1-2 MIN", notes: "KNEES TO CHEST, CONTROLLED REPS, STRAIGHTEN LEGS MORE TO INCREASE DIFFICULTY" },
        { id: "w9d4e4", name: "LAT PULL-OVER", warmupSets: 1, workingSets: 3, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "CAN USE A DB, CABLE/ROPE OR BAND, STRETCH AND SQUEEZE LATS!" },
        { id: "w9d4e5", name: "INCLINE DUMBBELL CURL", warmupSets: 1, workingSets: 2, reps: "12-15", rpe: "9", rest: "1-2 MIN", notes: "DO EACH ARM ONE AT A TIME RATHER THAN ALTERNATING, START WITH YOUR WEAK ARM" },
        { id: "w9d4e6", name: "FACE PULL", warmupSets: 0, workingSets: 4, reps: "15-20", rpe: "9", rest: "1-2 MIN", notes: "CAN USE CABLE/ROPE OR BAND, RETRACT YOUR SHOULDER BLADES AS YOU PULL" },
      ],
    },
    {
      id: "w9d5",
      name: "Day 5 — Full Body 4: Deadlift, Bench Press",
      source: "powerbuilding",
      exercises: [
        { id: "w9d5e1", name: "PAUSE DEADLIFT", warmupSets: 4, workingSets: 4, reps: "2", percent1RM: "75%", rest: "3-4 MIN", notes: "3 SECOND PAUSE RIGHT AFTER THE PLATES COME OFF THE GROUND" },
        { id: "w9d5e2", name: "PAUSE BARBELL BENCH PRESS", warmupSets: 3, workingSets: 3, reps: "5", percent1RM: "77.5%", rest: "2-3 MIN", notes: "2-3 SECOND PAUSE ON THE CHEST" },
        { id: "w9d5e3", name: "CHEST-SUPPORTED T-BAR ROW OR PENDLAY ROW", warmupSets: 1, workingSets: 3, reps: "10", rpe: "7", rest: "1-2 MIN", notes: "BE MINDFUL OF LOWER BACK FATIGUE. STAY LIGHT, MINIMIZE CHEATING" },
        { id: "w9d5e4", name: "NORDIC HAM CURL", warmupSets: 0, workingSets: 3, reps: "6-8", rpe: "8", rest: "1-2 MIN", notes: "BEND FORWARD AT HIPS DURING THE CONCENTRIC AND MINIMIZE CONTRIBUTION FROM HANDS" },
        { id: "w9d5e5", name: "DUMBBELL SHRUG", warmupSets: 0, workingSets: 3, reps: "20-25", rpe: "9", rest: "1-2 MIN", notes: "FEEL A STRETCH ON THE TRAPS AT THE BOTTOM, SQUEEZE HARD AT THE TOP" },
      ],
    },
    {
      id: "w9d6",
      name: "Day 6 — Supplemental A (Arms)",
      source: "arms",
      note: "Take the last set of each exercise to failure.",
      exercises: [
        { id: "w9d6e1", name: "Dumbbell Concentration Curl", workingSets: 4, reps: "8-10", tempo: "2.0.1.0", rpe: "9", rest: "2.0", notes: "Elbow pinned against thigh, rotating grip (supinate through the concentric)." },
        { id: "w9d6e2", name: "Standing EZ Bar Curl (Descending ROM)", workingSets: 2, reps: "10+5+5", rpe: "9", rest: "1.5", notes: "10 reps full ROM, 5 reps top end ROM, 5 reps bottom end ROM." },
        { id: "w9d6e3", name: "Weighted Dip (Close Grip)", workingSets: 3, reps: "12-15", tempo: "2.0.1.0", rpe: "8", rest: "2.0", notes: "More upright posture, mind-muscle connection with the triceps." },
        { id: "w9d6e4", name: "1-Arm Overhead Cable Extension", workingSets: 2, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Keep your elbow locked into place and tucked in." },
        { id: "w9d6e5", name: "Reverse Grip Forearm Wrist Curl (optional)", workingSets: 3, reps: "15-20", tempo: "2.0.1.0", rpe: "9", rest: "1.0", notes: "Optional. Forearm braced on a horizontal bench." },
      ],
    },
    ],
  },
  {
    id: "w10",
    name: "Week 10 (Max Test · Option A)",
    days: [
    {
      id: "w10d1",
      name: "Day 1 — Squat Test",
      source: "powerbuilding",
      exercises: [
        { id: "w10d1e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 1, reps: "AMRAP", percent1RM: "90%", rpe: "9.5", rest: "4-5 MIN", notes: "AS MANY REPS AS POSSIBLE. ALWAYS USE A SPOTTER AND GOOD FORM. AIM TO 3+ REPS" },
        { id: "w10d1e2", name: "SINGLE-ARM LAT PULLDOWN", warmupSets: 1, workingSets: 2, reps: "12", rpe: "8", rest: "2-3 MIN", notes: "PERFORM WITH BANDS IF NO LAT PULLDOWN, DRIVE ELBOWS DOWN AND IN" },
        { id: "w10d1e3", name: "INCLINE DUMBBELL CURL", warmupSets: 0, workingSets: 4, reps: "12", rpe: "8", rest: "1-2 MIN", notes: "FOCUS ON THE MIND-MUSCLE CONNECTION" },
        { id: "w10d1e4", name: "STANDING CALF RAISE", warmupSets: 1, workingSets: 3, reps: "12", rpe: "8", rest: "1-2 MIN", notes: "1-2 SECOND PAUSE AT THE BOTTOM OF EACH REP, FULL SQUEEZE AT THE TOP" },
      ],
    },
    {
      id: "w10d2",
      name: "Day 2 — Bench Test",
      source: "powerbuilding",
      exercises: [
        { id: "w10d2e1", name: "BARBELL BENCH PRESS", warmupSets: 4, workingSets: 1, reps: "AMRAP", percent1RM: "90%", rpe: "9.5", rest: "4-5 MIN", notes: "AS MANY REPS AS POSSIBLE. ALWAYS USE A SPOTTER AND GOOD FORM. AIM TO 3+ REPS" },
        { id: "w10d2e2", name: "LEG CURL", warmupSets: 1, workingSets: 3, reps: "8-10", rpe: "8", rest: "2-3 MIN", notes: "DO LYING LEG CURL MACHINE OR NORDIC HAM CURL IF NO MACHINE ACCESS" },
        { id: "w10d2e3", name: "DUMBBELL LATERAL RAISE", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "8", rest: "1-2 MIN", notes: "ARC THE DUMBBELL OUT, MIND-MUSCLE CONNECTION WITH MIDDLE FIBERS" },
        { id: "w10d2e4", name: "TRICEPS PRESSDOWN", warmupSets: 1, workingSets: 3, reps: "12", rpe: "8", rest: "1-2 MIN", notes: "CAN DO WITH CABLES OR BANDS, SQUEEZE TRICEPS TO MOVE THE WEIGHT" },
      ],
    },
    {
      id: "w10d3",
      name: "Day 3 — Deadlift Test",
      source: "powerbuilding",
      exercises: [
        { id: "w10d3e1", name: "DEADLIFT", warmupSets: 4, workingSets: 1, reps: "AMRAP", percent1RM: "90%", rpe: "9.5", rest: "4-5 MIN", notes: "AS MANY REPS AS POSSIBLE. ALWAYS USE GOOD FORM. AIM TO 3+ REPS" },
        { id: "w10d3e2", name: "OVERHEAD PRESS", warmupSets: 2, workingSets: 3, reps: "10", rpe: "6", rest: "2-3 MIN", notes: "RESET EACH REP (DON'T TOUCH-AND-PRESS)" },
        { id: "w10d3e3", name: "LEG EXTENSION", warmupSets: 1, workingSets: 3, reps: "12", rpe: "7", rest: "1-2 MIN", notes: "USE BANDS IF NO MACHINE ACCESS, MIND-MUSCLE CONNECTION WITH QUADS" },
        { id: "w10d3e4", name: "BICYCLE CRUNCH", warmupSets: 0, workingSets: 4, reps: "15", rpe: "8", rest: "1-2 MIN", notes: "FOCUS ON ROUNDING YOUR BACK AS YOU CRUNCH HARD!" },
      ],
    },
    ],
  },
  {
    id: "w11",
    name: "Week 11 (Deload)",
    days: [
    {
      id: "w11d1",
      name: "Day 1 — Lower #1",
      source: "powerbuilding",
      exercises: [
        { id: "w11d1e1", name: "DEADLIFT", warmupSets: 4, workingSets: 2, reps: "3", percent1RM: "75%", rest: "3-5 MIN", notes: "BRACE YOUR LATS, CHEST TALL, PULL THE SLACK OUT OF THE BAR BEFORE LIFTING" },
        { id: "w11d1e2", name: "SUMO BOX SQUAT OR PAUSE HIGH-BAR SQUAT", warmupSets: 2, workingSets: 2, reps: "6", rpe: "5", rest: "2-3 MIN", notes: "IF YOU SQUAT HIGH-BAR, DO SUMO BOX SQUAT. IF YOU SQUAT LOW-BAR, DO PAUSE HIGH-BAR (2 SEC PAUSE)" },
        { id: "w11d1e3", name: "LEG CURL", warmupSets: 1, workingSets: 2, reps: "6-8", rpe: "6", rest: "1-2 MIN", notes: "DO LYING LEG CURL MACHINE OR NORDIC HAM CURL IF NO MACHINE ACCESS" },
        { id: "w11d1e4", name: "STANDING CALF RAISE", warmupSets: 1, workingSets: 2, reps: "8-10", rpe: "6", rest: "1-2 MIN", notes: "1-2 SECOND PAUSE AT THE BOTTOM OF EACH REP, FULL SQUEEZE AT THE TOP" },
        { id: "w11d1e5", name: "HANGING LEG RAISE", warmupSets: 0, workingSets: 2, reps: "10-12", rpe: "6", rest: "1-2 MIN", notes: "KNEES TO CHEST, CONTROLLED REPS, STRAIGHTEN LEGS MORE TO INCREASE DIFFICULTY" },
      ],
    },
    {
      id: "w11d2",
      name: "Day 2 — Upper #1",
      source: "powerbuilding",
      exercises: [
        { id: "w11d2e1", name: "BARBELL BENCH PRESS", warmupSets: 3, workingSets: 2, reps: "6", percent1RM: "72.5%", rest: "3-4 MIN", notes: "SET UP A COMFORTABLE ARCH, SLIGHT PAUSE ON THE CHEST, EXPLODE UP" },
        { id: "w11d2e2", name: "ASSISTED CHIN-UP", warmupSets: 1, workingSets: 2, reps: "8-10", rpe: "7", rest: "2-3 MIN", notes: "UNDERHAND GRIP, PULL YOUR CHEST TO THE BAR, ADD WEIGHT IF NEEDED TO HIT RPE" },
        { id: "w11d2e3", name: "OVERHEAD PRESS", warmupSets: 2, workingSets: 2, reps: "4", percent1RM: "75%", rest: "2-3 MIN", notes: "SQUEEZE YOUR GLUTES TO KEEP YOUR TORSO UPRIGHT, PRESS UP AND SLIGHTLY BACK" },
        { id: "w11d2e4", name: "CHEST-SUPPORTED DUMBBELL ROW", warmupSets: 1, workingSets: 2, reps: "12-15", rpe: "7", rest: "1-2 MIN", notes: "LIE ON AN INCLINE BENCH AND DO ROWS - PULL WITH LATS!" },
        { id: "w11d2e5", name: "A1: FACE PULL", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "8", rest: "30SEC", notes: "CAN USE CABLE/ROPE OR BAND, RETRACT YOUR SHOULDER BLADES AS YOU PULL" },
        { id: "w11d2e6", name: "A2: DUMBBELL LATERAL RAISE", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "8", rest: "30SEC", notes: "ARC THE DUMBBELL OUT, MIND-MUSCLE CONNECTION WITH MIDDLE FIBERS" },
        { id: "w11d2e7", name: "B1: CONCENTRATION BICEP CURL", warmupSets: 0, workingSets: 2, reps: "12-15", rpe: "8", rest: "30SEC", notes: "PIN YOUR ELBOW AGAINST YOUR UPPER LEG OR THE BACK OF A BENCH" },
        { id: "w11d2e8", name: "B2: TRICEPS PRESSDOWN", warmupSets: 0, workingSets: 2, reps: "12-15", rpe: "8", rest: "30SEC", notes: "CAN DO WITH CABLES OR BANDS, SQUEEZE TRICEPS TO MOVE THE WEIGHT" },
      ],
    },
    {
      id: "w11d3",
      name: "Day 3 — Lower # 2",
      source: "powerbuilding",
      exercises: [
        { id: "w11d3e1", name: "BACK SQUAT", warmupSets: 4, workingSets: 2, reps: "6", percent1RM: "70%", rest: "3-4 MIN", notes: "SIT BACK AND DOWN, KEEP YOUR UPPER BACK TIGHT TO THE BAR" },
        { id: "w11d3e2", name: "SNATCH-GRIP ROMANIAN DEADLIFT", warmupSets: 2, workingSets: 2, reps: "8", rpe: "6", rest: "2-3 MIN", notes: "WIDE GRIP, MIND-MUSCLE CONNECTION WITH HAMSTRINGS" },
        { id: "w11d3e3", name: "LEG EXTENSION", warmupSets: 1, workingSets: 2, reps: "12-15", rpe: "7", rest: "1-2 MIN", notes: "USE BANDS IF NO MACHINE ACCESS, MIND-MUSCLE CONNECTION WITH QUADS" },
        { id: "w11d3e4", name: "STANDING CALF RAISE", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "8", rest: "1-2 MIN", notes: "EMPHASIZE THE MIND-MUSCLE CONNECTION" },
        { id: "w11d3e5", name: "BANDED LATERAL WALK OR HIP ABDUCTION", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "8", rest: "1-2 MIN", notes: "POINT TOES SLIGHTLY OUTWARD, MIND-MUSCLE CONNECTION WITH GLUTES" },
        { id: "w11d3e6", name: "V SIT-UP", warmupSets: 0, workingSets: 2, reps: "12-15", rpe: "8", rest: "1-2 MIN", notes: "THINK ABOUT SQUEEZING YOUR UPPER AND LOWER ABS TOGETHER" },
        { id: "w11d3e7", name: "NECK FLEXION/EXTENSION (OPTIONAL)", warmupSets: 1, workingSets: 2, reps: "12/12", rpe: "8", rest: "1-2 MIN", notes: "12 REPS FLEXION (FRONT OF NECK), 12 REPS EXTENSION (BACK OF NECK)" },
      ],
    },
    {
      id: "w11d4",
      name: "Day 4 — Upper #2",
      source: "powerbuilding",
      exercises: [
        { id: "w11d4e1", name: "CLOSE-GRIP BENCH PRESS", warmupSets: 3, workingSets: 3, reps: "10", rpe: "6", rest: "2-3 MIN", notes: "SHOULDER WIDTH GRIP, TUCK YOUR ELBOWS IN CLOSER TO YOUR TORSO" },
        { id: "w11d4e2", name: "CHEST-SUPPORTED DUMBBELL ROW", warmupSets: 1, workingSets: 2, reps: "10", rpe: "6", rest: "3-4 MIN", notes: "LIE ON AN INCLINE BENCH AND DO ROWS - PULL WITH LATS!" },
        { id: "w11d4e3", name: "WEIGHTED DIP", warmupSets: 2, workingSets: 2, reps: "6", rpe: "7", rest: "2-3 MIN", notes: "DO DUMBBELL FLOOR PRESS IF NO ACCESS TO DIP HANDLES" },
        { id: "w11d4e4", name: "SINGLE-ARM LAT PULLDOWN", warmupSets: 1, workingSets: 2, reps: "10", rpe: "8", rest: "2-3 MIN", notes: "PERFORM WITH BANDS IF NO LAT PULLDOWN, DRIVE ELBOWS DOWN AND IN" },
        { id: "w11d4e5", name: "A1. INCLINE SHRUG", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "8", rest: "30SEC", notes: "LIE FACE DOWN AGAINST AN INCLINE BENCH AND DO SHRUGS - FULL ROM AND SQUEEZE!" },
        { id: "w11d4e6", name: "A2. UPRIGHT ROW", warmupSets: 0, workingSets: 2, reps: "15-20", rpe: "8", rest: "30SEC", notes: "CAN USE CABLES/ROPE, BANDS OR DUMBBELLS. STOP ROM ONCE ELBOWS REACH SHOULDER HEIGHT." },
        { id: "w11d4e7", name: "B1: BARBELL OR EZ BAR CURL", warmupSets: 0, workingSets: 2, reps: "12-15", rpe: "8", rest: "30SEC", notes: "FOCUS ON THE MIND-MUSCLE CONNECTION" },
        { id: "w11d4e8", name: "B2. SKULL CRUSHER", warmupSets: 0, workingSets: 2, reps: "8-10", rpe: "8", rest: "30SEC", notes: "BARBELL OR EZ BAR, DO THESE ON A BENCH, CONSTANT TENSION ON TRICEPS" },
        { id: "w11d4e9", name: "A2. FLOOR SKULL CRUSHER", warmupSets: 1, workingSets: 3, reps: "12", rpe: "8", rest: "30SEC", notes: "ARC THE BAR BACK BEHIND YOUR HEAD, SOFT TOUCH ON THE FLOOR BEHIND YOU" },
      ],
    },
    ],
  },
  ],
  custom: [],
};
